package er.ajax;

// Generated by the WOLips Templateengine Plug-in at 11.08.2006 13:19:58
// http://jquery.com/demo/thickbox/

import com.webobjects.appserver.WOElement;
import com.webobjects.foundation.NSDictionary;

/**
 * @see AjaxModalContainer
 * @see AjaxModalDialog
 * @deprecated use {@link AjaxModalContainer} or {@link AjaxModalDialog}
 */
@Deprecated
public class AjaxIBoxComponentContent extends AjaxModalContainer {

	public AjaxIBoxComponentContent(String name, NSDictionary associations, WOElement children) {
		super(name, associations, children);
	}
}
