package er.seleniumexample;
// Generated by the WOLips Templateengine Plug-in at 11.05.2007 18:46:51

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
    
	public Main(WOContext context) {
        super(context);
    }

    public WOComponent showAction() {
    	return pageWithName(Message.class.getName());
    }
}