// Generated by the WebObjects Wizard
package er.reporting.examples;

import java.util.Date;

import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;

import er.extensions.appserver.ERXApplication;
import er.grouping.DRReportModel;


public class Application extends ERXApplication { 

public static void main(String argv[]) {
        ERXApplication.main(argv, Application.class);
    }

    public String path;
    public String modelDictString;
    public String modelDictString2;

    public String pathString(){
	return path;
    }


    public Application() throws Exception {
        super();
        System.out.println("Welcome to " + this.name() + " !");
        /* ** put your initialization code in here ** */
        path = resourceManager().pathForResourceNamed("GROUP_BYReportModel.dat", null, null);
        modelDictString = DRReportModel.stringContentsOfFile(path);
        path = resourceManager().pathForResourceNamed("SimpleReportModel.dat", null, null);
        modelDictString2 = DRReportModel.stringContentsOfFile(path);
    }
    
    public WOResponse dispatchRequest(WORequest r){
        Date ts1 = new Date();
        long ts1L = ts1.getTime();
        //System.out.println("ts1L: "+ts1L);
        WOResponse rp = super.dispatchRequest(r);
        Date ts2 = new Date();
        long ts2L = ts2.getTime();
        //System.out.println("ts2L: "+ts1L);
        long delta = ts2L - ts1L;
        System.out.println("delta: "+(double)delta/(double)1000.0);
        return rp;
    }

}
