// Generated by the WebObjects Wizard Mon Mar 22 11:50:44 US/Central 1999
package er.reporting.examples;

import er.reporting.*;
import er.grouping.*;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;

public class GroupingOnlyDoc extends WOComponent {

    public GroupingOnlyDoc(WOContext c){
        super(c);
    }


}
