// Generated by the WebObjects Wizard Wed Jan 27 21:17:53 US/Central 1999

package er.reporting.examples;

import er.reporting.*;
import er.grouping.*;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;

public class GroupByPage extends WOComponent {

    public GroupByPage(WOContext c){
        super(c);
        Session s = (Session)session();
        s.getRawRows ();
        rebuildReport();
    }

    public void rebuildReport(){
        Session s = (Session)session();
        NSArray aCritArray2 = (NSArray) s.valueForKey("critArray2");
        NSArray aAttribList2 = (NSArray) s.valueForKey("attribArray2");
        NSArray objs = (NSArray) s.groupByRows;
        DRReportModel mod = DRReportModel.withRawRecordsCriteriaListAttributeList(objs, aCritArray2, aAttribList2);
        s.reportModel2 = mod;
    }
    public WOComponent rebuild(){
	rebuildReport ();
	return null;
    }

}
