// Generated by the WebObjects Wizard Mon Mar 22 11:50:35 US/Central 1999
package er.reporting.examples;

import er.reporting.*;
import er.grouping.*;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;

public class QuickReportTestDoc extends WOComponent {

    public QuickReportTestDoc(WOContext c){
        super(c);
    }



    public WOComponent doNothing() {
        return null;
    }

}
