package er.indexing.example;
// Generated by the WOLips Templateengine Plug-in at 12.06.2008 11:20:01

import com.webobjects.foundation.NSLog;

import er.extensions.appserver.ERXApplication;

public class Application extends ERXApplication {
	
	public static void main(String argv[]) {
		ERXApplication.main(argv, Application.class);
	}

	@Override
	public void finishInitialization() {
	    super.finishInitialization();
        //DataCreator.main(null);
        //ERIndexing.indexing().loadIndexDefinitions();
	}
	
	public Application() {
		NSLog.out.appendln("Welcome to " + name() + " !");
	}
}