package er.indexing.example;
// Generated by the WOLips Templateengine Plug-in at 12.06.2008 11:20:01

import com.webobjects.foundation.NSLog;

import er.extensions.appserver.ERXApplication;
import er.indexing.ERIndexModel;

public class Application extends ERXApplication {
	
	public static ERIndexModel model;
	
	public static void main(String argv[]) {
		ERXApplication.main(argv, Application.class);
	}

	public Application() {
		NSLog.out.appendln("Welcome to " + this.name() + " !");
		DataCreator.main(null);
		if(model == null) {
			model = ERIndexModel.indexModel();
		}
	}
}