package er.indexing.example;
// Generated by the WOLips Templateengine Plug-in at 12.06.2008 11:20:01

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
	public Session() {
	}
}