package er.seleniumexample;
// Generated by the WOLips Templateengine Plug-in at 11.05.2007 18:41:07

import er.extensions.ERXApplication;

public class Application extends ERXApplication {
    
    public static void main(String argv[]) {
        ERXApplication.main(argv, Application.class);
    }

    public Application() {
        super();
    }
}