package er.seleniumexample;
// Generated by the WOLips Templateengine Plug-in at 11.05.2007 18:47:22

import com.webobjects.appserver.*;

public class Message extends WOComponent {

    public Message(WOContext context) {
        super(context);
    }
}