// Generated by the WebObjects Wizard Tue Jul 10 19:06:31 America/Los_Angeles 2001
package er.directtoweb;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;
import com.webobjects.directtoweb.*;

public class ERD2WDisplayToManyList extends D2WDisplayToManyTable {
public ERD2WDisplayToManyList(WOContext context) {super(context);}
}
