// Generated by the WebObjects Wizard Thu Nov 15 17:04:25 America/Los_Angeles 2001
package er.directtoweb;

import com.webobjects.appserver.*;
import com.webobjects.directtoweb.*;
import er.extensions.*;

public class ERDEmptyPageWrapper extends ERXStatelessComponent {
public ERDEmptyPageWrapper(WOContext context) {super(context);}
}
