// Generated by the WebObjects Wizard Fri Dec 28 16:01:46 America/Los_Angeles 2001
package er.directtoweb;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;

public class ERDQueryDateRangeJavascript extends WOComponent {
public ERDQueryDateRangeJavascript(WOContext context) {super(context);}


   protected static final NSTimestampFormatter DATE_FORMAT =
        new NSTimestampFormatter("%m/%d/%Y") /* JC_WARNING - Removed the ommit natural language flag "<e2>".*/;
    protected static final NSTimestampFormatter DATE_FORMAT_YEAR_TWO_DIGITS =
        new NSTimestampFormatter("%m/%d/%y") /* JC_WARNING - Removed the ommit natural language flag "<e2>".*/;

    protected WODisplayGroup _displayGroup;
    protected String key;

    public String propertyKey() {
        return key;
    }

    public WODisplayGroup displayGroup() {
        return _displayGroup;
    }

    private String stringForDate(NSTimestamp d) {
        String result=null;
        if(d != null) {
            try {
                result = DATE_FORMAT.format(d);
            } catch(IllegalArgumentException /* JC_WARNING - You may want to use NumberFormatException instead.*/ nsfe) {}
        }
        return result;
    }
    
    private String _minValue;
    public Object minValue() {
        if(_minValue == null){
            _minValue=stringForDate((NSTimestamp)displayGroup().queryMin().valueForKey(propertyKey()));
        }
        return _minValue;
    }

    private String _maxValue;
    public Object maxValue() {
        if(_maxValue == null){
            _maxValue=stringForDate((NSTimestamp)displayGroup().queryMax().valueForKey(propertyKey()));
        }
        return _maxValue;
    }


    public NSTimestamp dateForString(String dateString) {
        NSTimestamp date = null;
        try {
            if(dateString!=null) {
                boolean dateIsValid = false;
                NSMutableArray components = new NSMutableArray(NSArray.componentsSeparatedByString(dateString, "/"));
                if (components.count() == 3) {
                    String monthString = (String)components.objectAtIndex(0);
                    if (monthString.length() == 1)
                        components.replaceObjectAtIndex(0, "0" + monthString);
                    String dayString = (String)components.objectAtIndex(1);
                    if (dayString.length() == 1)
                        components.replaceObjectAtIndex(1, "0" +dayString);
                    String yearString = (String)components.objectAtIndex(2);
                    //String yearString = dateString.substring(dateString.lastIndexOf("/")+1, dateString.length());
                    String modifiedDateString = components.componentsJoinedByString("/");
                    java.text.Format formatter=yearString.length()==2 ? DATE_FORMAT_YEAR_TWO_DIGITS : DATE_FORMAT;
                    date = (NSTimestamp) formatter.parseObject(modifiedDateString);
                    String reformattedDate=formatter.format(date);
                    dateIsValid = reformattedDate.equals(modifiedDateString);
                }
                if (!dateIsValid)
                    throw new NSValidation.ValidationException("Please check <B>"+
                                                     valueForBinding("displayNameForProperty")+"</B>: "+dateString+" is not a valid date");
                
            }
        } catch (java.text.ParseException nspe) {
            NSValidation.ValidationException v =
            new NSValidation.ValidationException("Please check the format of <B>"+
                                       valueForBinding("displayNameForProperty")+"</B> "+dateString+" is not a valid date");
            parent().validationFailedWithException( v, date, propertyKey());
        } catch (NSValidation.ValidationException v) {
            parent().validationFailedWithException(v,date,propertyKey());
        } catch(Exception e) {
            parent().validationFailedWithException(e,date,propertyKey());
        }

        return date;
    }


    
    public void setMinValue(String min) {
        _minValue=min;
        displayGroup().queryMin().takeValueForKey(dateForString(min), propertyKey());
    }

    public void setMaxValue(String max) {
        _maxValue=max;
        displayGroup().queryMax().takeValueForKey(dateForString(max), propertyKey());
    }
        
    private static String _datePickerJavaScriptUrl;
    public String datePickerJavaScriptUrl() {
        if (_datePickerJavaScriptUrl==null) {
            _datePickerJavaScriptUrl= application().resourceManager().urlForResourceNamed("date-picker.js",
                                                                                          "ERExtensions",
                                                                                          null,
                                                                                          context().request());
          }
        return _datePickerJavaScriptUrl;
      }


    private String _minName;
    public String minName() {
        if (_minName==null) _minName="min"+propertyKey();
        return _minName;
    }
    private String _maxName;
    public String maxName() {
        if (_maxName==null) _maxName="max"+propertyKey();
        return _maxName;
    }
}
