package er.sproutcore.example.components;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at 10.07.2008 20:59:32
public class HelloWorld extends com.webobjects.appserver.WOComponent {
    public HelloWorld(WOContext context) {
        super(context);
    }
}