package er.sproutcore.example.components;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at 15.07.2008 13:01:30
public class PageWrapper extends com.webobjects.appserver.WOComponent {
    public PageWrapper(WOContext context) {
        super(context);
    }
}