package er.iui.components;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Apr 2, 2008 10:54:30 PM

/**
 *
 * @binding title
 */
public class ERIUIPreferenceGroup extends ERXComponent {
  public ERIUIPreferenceGroup(WOContext context) {
    super(context);
  }

  @Override
  public boolean synchronizesVariablesWithBindings() {
    return false;
  }
}
