// Generated by the WOLips Templateengine Plug-in at Feb 12, 2007 1:13:37 PM

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

import er.ajax.*;

public class AjaxGridExampleNavBar extends AjaxGridNavBar {

	public NSArray batchSizes = new NSArray(new String[] { "2", "4", "6", "8", "10" });
	public String batchSize;

	public AjaxGridExampleNavBar(WOContext context) {
		super(context);
	}

	/**
	 * @return value for BatchSizes from application configuration
	 */
	public NSArray batchSizes() {
		return batchSizes;
	}
}