// Generated by the WOLips Templateengine Plug-in at 09.03.2006 16:24:23

import org.apache.log4j.Logger;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

import er.ajax.json.JSONRequestHandler;
import er.extensions.appserver.ERXApplication;

public class Application extends ERXApplication {
	static Logger log = Logger.getLogger(Application.class);

	public static void main(String argv[]) {
		ERXApplication.main(argv, Application.class);
	}

	public Application() {
		super();
		log.info("Welcome to " + this.name() + " !");
		/* ** put your initialization code in here ** */
		setAllowsConcurrentRequestHandling(true);
		setDefaultRequestHandler(requestHandlerForKey(directActionRequestHandlerKey()));
		JSONRequestHandler requestHandler = JSONRequestHandler.register();
		requestHandler.registerService("exampleService", new ExampleService());
	}
	
	
	public WOResponse dispatchRequest(WORequest request) {
		boolean isActionRequest = request.uri().indexOf("/wo/") > -1 || request.uri().indexOf("/wa/") > -1 || request.uri().indexOf("/ajax/") > -1;
		isActionRequest = false;  // Comment this out to enable debug logging
		if (isActionRequest) {
			NSLog.out.appendln("---- start of RR loop ----\n");
			if (request.uri().indexOf("/wo/") > -1) log.info("Received component action request " + request.uri());
			else if (request.uri().indexOf("/wa/") > -1) log.info("Received direct action request " + request.uri());
			else if (request.uri().indexOf("/ajax/") > -1) log.info("Received ajax action request " + request.uri());
			
			WOResponse response =  super.dispatchRequest(request);
			
	    	NSLog.out.appendln("returned response " + response.contentString());
	    	NSLog.out.appendln("returned response headers " + response.headers());
	    	NSLog.out.appendln("\n");
	    	return response;
		}

		return super.dispatchRequest(request);
	}
	
}