// Generated by the WOLips Templateengine Plug-in at Feb 7, 2007 9:27:22 PM

import com.webobjects.appserver.*;

public class GridCellComponent extends WOComponent {

	public String value;
	
    public GridCellComponent(WOContext context) {
        super(context);
    }

}