// Generated by the WOLips Templateengine Plug-in at 27.03.2006 10:13:46

import com.metaparadigm.dict.DictClient;
import com.webobjects.appserver.*;

public class ProxyExample extends WOComponent {
    
    private int _counter = 0;
    private DictClient _dict;
    
    public ProxyExample(WOContext context) {
        super(context);
    }

    public int addMore(int x) {
        return _counter = _counter + x;
    }
    
    public int add() {
        return ++_counter;
    }
    
    public DictClient dict() {
        if (_dict == null) {
            _dict = new DictClient("dict.die.net");
        }
        return _dict;
    }
}