// Generated by the WOLips Templateengine Plug-in at Apr 28, 2006 4:18:15 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class RoundedBordersExample extends WOComponent {

  public RoundedBordersExample(WOContext context) {
    super(context);
  }

}