// Generated by the WOLips Templateengine Plug-in at 27.03.2006 12:08:47

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class SliderExample extends WOComponent {

    public SliderExample(WOContext context) {
        super(context);
    }

}