// Generated by the WOLips Templateengine Plug-in at Jun 6, 2007 4:50:53 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSTimestamp;

public class UpdateContainerInContainer extends WOComponent {

	public UpdateContainerInContainer(WOContext context) {
		super(context);
	}

	public NSTimestamp now() {
		return new NSTimestamp();
	}
}