// Generated by the WOLips Templateengine Plug-in at Feb 16, 2007 12:44:09 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class UpdateWindow extends WOComponent {

    public UpdateWindow(WOContext context) {
        super(context);
    }

}