package er.bugtracker.components.reporting;

// Generated by the WOLips Templateengine Plug-in at 30.05.2007 07:59:44

import org.apache.log4j.Logger;

import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSDictionary;
import com.webobjects.foundation.NSTimestamp;

import er.grouping.DRRecordGroup;
import er.reporting.WRReport;

public class Report extends WRReport {
    private static final Logger log = Logger.getLogger(Report.class);

    public Report(WOContext context) {
        super(context);
    }

    /** component does not synchronize it's variables */
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }

    public Object handleQueryWithUnboundKey(String key) {
        log.error("handleQueryWithUnboundKey: " + key, new RuntimeException("Stacktrace"));
        return null;
    }

    public void handleTakeValueWithUnboundKey(Object o, String key) {
        log.error(key);
    }

    public String classAttributeTd() {
        return "WRAttribute" + depth + "Total" + this.totalCount();
    }

    public NSTimestamp startDate() {
        return (NSTimestamp) valueForBinding("startDate");
    }

    public NSTimestamp endDate() {
        return (NSTimestamp) valueForBinding("endDate");
    }

    public DRRecordGroup recordGroup() {
        NSDictionary crds = this.currentCoordinates();
        DRRecordGroup drg = this.model().recordGroupForCoordinates(crds);
        return drg;
    }
}