// Generated by the WebObjects Wizard Tue Sep 04 14:55:14 America/Los_Angeles 2001
package er.extensions;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// this admittedly simple component is sometimes useful for use in WOSwitchComponents
public class ERXEmptyComponent extends WOComponent {

    public ERXEmptyComponent(WOContext aContext) {
        super(aContext);
    }
    
    public boolean isStateless() { return true; }
}
