package er.extensions;
// Generated by the WOLips Templateengine Plug-in at 08.08.2007 09:49:26

import com.webobjects.appserver.*;
import com.webobjects.woextensions.WOStatsPage;

public class ERXStatisticsPage extends WOStatsPage {

    public ERXStatisticsPage(WOContext context) {
        super(context);
    }

}