// Generated by the WebObjects Wizard Fri Aug 31 15:55:33 America/Los_Angeles 2001
package er.directtoweb;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;
import com.webobjects.directtoweb.*;

public class ERD2WEditPercentage extends D2WEditNumber {

    public ERD2WEditPercentage(WOContext context) {
        super(context);
    }

}
