// Generated by the WebObjects Wizard Fri Jan 04 15:13:44 America/Los_Angeles 2002
package er.directtoweb;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;
import com.webobjects.directtoweb.*;


public class ERD2WPickFromEntities extends ERDCustomQueryComponent {

    public ERD2WPickFromEntities(WOContext context) {
        super(context);
    }
    
    public static D2WContext _d2wContext=new D2WContext(); 
    
    // lets you pick from either an arbitrary list or a pool of shared EOs  
    public Object item; 

    // can't be stateless!
    public boolean isStateless() { return false; }
    public boolean synchronizesVariablesWithBindings() { return false; }

    public NSArray list() {
        return (NSArray)valueForBinding("list");            
    }

    public String displayString() {
        String result=null;
        if (item!=null) {
            _d2wContext.setEntity(EOModelGroup.defaultGroup().entityNamed((String)item));
            result=(String)_d2wContext.valueForKey("displayNameForEntity");
        }
        return result;
    }
    
}
