package er.directtoweb;
// Generated by the WOLips Templateengine Plug-in at 05.06.2007 22:03:47

import com.webobjects.appserver.WOContext;

import er.extensions.ERXProperties;

/**
 * Very, very basic version of a TinyMCE integration. As it doesn't make much sense to load the the JS files
 * it's excepted that you put them somewhere on your server with the property <code>ERDEditHTML.tinyMceSourceUrl</code>.
 * 
 * @author ak
 *
 */
public class ERDEditHTML extends ERDCustomEditComponent {

    public ERDEditHTML(WOContext context) {
        super(context);
    }
    
    public boolean isStateless() {
        return true;
    }
    
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }
    
    public String sourceUrl() {
        String url = (String) ERXProperties.stringForKeyWithDefault("ERDEditHTML.tinyMceSourceUrl", 
                "http://tinymce.moxiecode.com/tinymce/jscripts/tiny_mce/tiny_mce.js");
        return url;
    }

}