package er.directtoweb;
// Generated by the WOLips Templateengine Plug-in at 28.05.2007 11:00:34

import com.webobjects.appserver.*;

public class ERDHasChangesMarker extends ERDCustomEditComponent {

    public ERDHasChangesMarker(WOContext context) {
        super(context);
    }

    public boolean isStateless() {
        return true;
    }
}