CREATE TABLE "ERCHELP_TEXT" (
	"ID" INTEGER NOT NULL,
	"KEY_" VARCHAR(100) NOT NULL,
	"VALUE_" VARCHAR(1000)
);

CREATE TABLE "ERCLOG_ENTRY" (
	"CREATED" TIMESTAMP NOT NULL,
	"ID" INTEGER NOT NULL,
	"TEXT_" VARCHAR(10000000) NOT NULL,
	"USER_ID" INTEGER NOT NULL
);

CREATE TABLE "ERCPREFER" (
	"ID" INTEGER NOT NULL,
	"KEY_" VARCHAR(100) NOT NULL,
	"USER_ID" INTEGER,
	"VALUE_" VARCHAR(10000000)
);

CREATE TABLE "ERCSTATIC" (
	"ID" INTEGER NOT NULL,
	"KEY_" VARCHAR(100) NOT NULL,
	"VALUE_" VARCHAR(1000)
);

SET UNIQUE = 1000000 FOR "ERCHELP_TEXT";

SET UNIQUE = 1000000 FOR "ERCLOG_ENTRY";

SET UNIQUE = 1000000 FOR "ERCPREFER";

SET UNIQUE = 1000000 FOR "ERCSTATIC";

ALTER TABLE "ERCHELP_TEXT" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCLOG_ENTRY" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCPREFER" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCSTATIC" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;



CREATE TABLE "ERCMAIL_MESSAG" (
	"BCC_ADDR" VARCHAR(1000),
	"CC_ADDR" VARCHAR(1000),
	"CONTENT_GZIPPED" INTEGER NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	"DATE_SENT" TIMESTAMP,
	"EXCEPTION_REASON" VARCHAR(1000),
	"FROM_ADDR" VARCHAR(255) NOT NULL,
	"ID" INTEGER NOT NULL,
	"IS_READ" INTEGER NOT NULL,
	"LAST_MODIFIED" TIMESTAMP NOT NULL,
	"PLAIN_TEXT_" VARCHAR(10000000),
	"plain_text_compressed" BLOB,
	"REPLY_TO_ADDR" VARCHAR(1000),
	"SHOULD_ARCHIVE_SENT_MAIL" INTEGER NOT NULL,
	"MAIL_STATE_ID" VARCHAR(4) NOT NULL,
	"TEXT_" VARCHAR(10000000),
	"TEXT_COMPRESSED" BLOB,
	"TITLE" VARCHAR(255) NOT NULL,
	"TO_ADDR" VARCHAR(1000) NOT NULL,
	"X_MAILER" VARCHAR(255)
);

CREATE TABLE "ERCMAIL_MESSAG_ARCHIVE" (
	"BCC_ADDR" VARCHAR(1000),
	"CC_ADDR" VARCHAR(1000),
	"CONTENT_GZIPPED" INTEGER NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	"DATE_SENT" TIMESTAMP,
	"EXCEPTION_REASON" VARCHAR(1000) NOT NULL,
	"FROM_ADDR" VARCHAR(255) NOT NULL,
	"ID" INTEGER NOT NULL,
	"IS_READ" INTEGER NOT NULL,
	"LAST_MODIFIED" TIMESTAMP NOT NULL,
	"PLAIN_TEXT_" VARCHAR(10000000),
	"plain_text_compressed" BLOB,
	"REPLY_TO_ADDR" VARCHAR(1000),
	"SHOULD_ARCHIVE_SENT_MAIL" INTEGER NOT NULL,
	"MAIL_STATE_ID" VARCHAR(4) NOT NULL,
	"TEXT_" VARCHAR(10000000) NOT NULL,
	"TEXT_COMPRESSED" BLOB,
	"TITLE" VARCHAR(255) NOT NULL,
	"TO_ADDR" VARCHAR(1000) NOT NULL,
	"X_MAILER" VARCHAR(255)
);

CREATE TABLE "ERCMESSAG_ATTACH" (
	"FILE_PATH" VARCHAR(1000) NOT NULL,
	"ID" INTEGER NOT NULL,
	"MAIL_MESSAG_ID" INTEGER NOT NULL,
	"MIME_TYPE" VARCHAR(255) NOT NULL
);

SET UNIQUE = 1000000 FOR "ERCMAIL_MESSAG_ARCHIVE";

SET UNIQUE = 1000000 FOR "ERCMAIL_MESSAG";

SET UNIQUE = 1000000 FOR "ERCMESSAG_ATTACH";

ALTER TABLE "ERCMAIL_MESSAG" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCMAIL_MESSAG_ARCHIVE" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCMESSAG_ATTACH" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

