package com.webobjects.directtoweb._ajax;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2W;
import com.webobjects.directtoweb.D2WDisplayToManyTable;
import com.webobjects.directtoweb.InspectPageInterface;

// Generated by the WOLips Templateengine Plug-in at Jun 17, 2008 5:38:29 PM
public class D2WAjaxDisplayToManyList extends D2WDisplayToManyTable {
    public D2WAjaxDisplayToManyList(WOContext context) {
        super(context);
    }
    
    // accessors
    public boolean hasItems() {
    	return (list()!= null && list().count() > 0);
    }
    
    // actions(ajax)
    @Override
    public WOComponent inspectAction() {
        if(item == null) {
            return null;
        } else {
            InspectPageInterface inspectPage = (InspectPageInterface) D2W.factory().pageForConfigurationNamed("AjaxInspect" + item.entityName(), session());
            inspectPage.setObject(item);
            inspectPage.setNextPage(context().page());
            return (WOComponent)inspectPage;
        }
    }
}