// Generated by the WebObjects Wizard Mon Mar 22 11:50:44 US/Central 1999
package er.reporting.examples;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class GroupingOnlyDoc extends WOComponent {

    public GroupingOnlyDoc(WOContext c){
        super(c);
    }


}
