// Generated by the WebObjects Wizard Thu Dec 24 13:55:25 US/Central 1998
package er.reporting.examples;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;


public class Main extends WOComponent {

    public Main(WOContext c){
        super(c);
    }

}
