// Generated by the WebObjects Wizard Sun Feb 07 13:38:03 US/Central 1999
package er.reporting.examples;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;

public class QuickReportTest extends WOComponent {

	protected String pathString;
    public NSArray objects; // EOs fetched with a fetch spec
	public NSMutableArray colors;

	public QuickReportTest(WOContext c){
		super(c);
		Session s = (Session)session();
		objects = s.objects();
		colors = new NSMutableArray();
		colors.addObject("c6c3af");
		colors.addObject("b7af4b"); // b7af4b
		colors.addObject("d5ba27");
		colors.addObject("ffec00"); //ffec00
		pathString = application().resourceManager().pathForResourceNamed("TestReportModel.dat", null, null);
	}


}
