// Generated by the WebObjects Wizard Mon Mar 22 11:50:35 US/Central 1999
package er.reporting.examples;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class QuickReportTestDoc extends WOComponent {

    public QuickReportTestDoc(WOContext c){
        super(c);
    }



    public WOComponent doNothing() {
        return null;
    }

}
