package er.seleniumexample;
// Generated by the WOLips Templateengine Plug-in at 11.05.2007 18:41:07

import com.webobjects.appserver.*;

import er.extensions.ERXDirectAction;

public class DirectAction extends ERXDirectAction {

    public DirectAction(WORequest aRequest) {
        super(aRequest);
    }

    public WOActionResults defaultAction() {
        return pageWithName(Main.class.getName());
    }

}