// ==========================================================================
// Photos.Photo Fixtures
// ==========================================================================

require('core') ;

Photos.FIXTURES = Photos.FIXTURES.concat(function() {

  var photoUrls = [
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN0005.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1063.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1068.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1076.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1083.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1084.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1099.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1180.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1279.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1316.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1332.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1338.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1359.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1360.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1368.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN2939.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN2945.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN2958.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3059.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3077.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3094.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3099.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3104.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3107.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3120.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3145.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3159.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3167.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3191.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3193.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3195.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3219.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3240.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3241.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3486.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3490.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3491.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3492.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3494.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3495.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3498.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3500.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3503.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3513.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3520.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3533.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3535.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3536.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3557.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3559.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3580.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3588.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3685.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3688.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3692.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3710.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3725.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3726.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3729.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3731.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3734.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3742.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3753.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3755.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3758.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3763.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3774.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3807.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3901.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN0005.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1063.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1068.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1076.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1083.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1084.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1099.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1180.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1279.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1316.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1332.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1338.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1359.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1360.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN1368.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN2939.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN2945.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN2958.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3059.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3077.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3094.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3099.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3104.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3107.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3120.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3145.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3159.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3167.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3191.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3193.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3195.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3219.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3240.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3241.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3486.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3490.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3491.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3492.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3494.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3495.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3498.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3500.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3503.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3513.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3520.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3533.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3535.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3536.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3557.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3559.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3580.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3588.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3685.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3688.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3692.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3710.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3725.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3726.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3729.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3731.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3734.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3742.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3753.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3755.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3758.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3763.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3774.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3807.jpg',
  '/cgi-bin/WebObjects/SproutCoreExample.woa/_sc_/SproutCore/common_assets/english.lproj/photos/DSCN3901.jpg'] ;
  
  var ret = [];
  var idx = PHOTO_COUNT ;
  while(--idx >= 0) {

    var photoUrlIdx = idx % photoUrls.length ;
    ret[ret.length] = { 
      guid: idx+1, 
      type: 'Photo',
      url: photoUrls[photoUrlIdx],
      name: photoUrls[photoUrlIdx].split('/').last(),
      rotation: 0,
      opacity: 1.0
    } ;
  }
  
  return ret.sort(function(a,b) { return (a.guid < b.guid) ? -1 : ((a.guid > b.guid) ? 1 : 0); }) ;
}());
