// ==========================================================================
// Photos.Photo Fixtures
// ==========================================================================

require('core') ;

Photos.FIXTURES = Photos.FIXTURES.concat(function() {

  var photoUrls = [
  static_url('photos/DSCN0005.jpg'),
  static_url('photos/DSCN1063.jpg'),
  static_url('photos/DSCN1068.jpg'),
  static_url('photos/DSCN1076.jpg'),
  static_url('photos/DSCN1083.jpg'),
  static_url('photos/DSCN1084.jpg'),
  static_url('photos/DSCN1099.jpg'),
  static_url('photos/DSCN1180.jpg'),
  static_url('photos/DSCN1279.jpg'),
  static_url('photos/DSCN1316.jpg'),
  static_url('photos/DSCN1332.jpg'),
  static_url('photos/DSCN1338.jpg'),
  static_url('photos/DSCN1359.jpg'),
  static_url('photos/DSCN1360.jpg'),
  static_url('photos/DSCN1368.jpg'),
  static_url('photos/DSCN2939.jpg'),
  static_url('photos/DSCN2945.jpg'),
  static_url('photos/DSCN2958.jpg'),
  static_url('photos/DSCN3059.jpg'),
  static_url('photos/DSCN3077.jpg'),
  static_url('photos/DSCN3094.jpg'),
  static_url('photos/DSCN3099.jpg'),
  static_url('photos/DSCN3104.jpg'),
  static_url('photos/DSCN3107.jpg'),
  static_url('photos/DSCN3120.jpg'),
  static_url('photos/DSCN3145.jpg'),
  static_url('photos/DSCN3159.jpg'),
  static_url('photos/DSCN3167.jpg'),
  static_url('photos/DSCN3191.jpg'),
  static_url('photos/DSCN3193.jpg'),
  static_url('photos/DSCN3195.jpg'),
  static_url('photos/DSCN3219.jpg'),
  static_url('photos/DSCN3240.jpg'),
  static_url('photos/DSCN3241.jpg'),
  static_url('photos/DSCN3486.jpg'),
  static_url('photos/DSCN3490.jpg'),
  static_url('photos/DSCN3491.jpg'),
  static_url('photos/DSCN3492.jpg'),
  static_url('photos/DSCN3494.jpg'),
  static_url('photos/DSCN3495.jpg'),
  static_url('photos/DSCN3498.jpg'),
  static_url('photos/DSCN3500.jpg'),
  static_url('photos/DSCN3503.jpg'),
  static_url('photos/DSCN3513.jpg'),
  static_url('photos/DSCN3520.jpg'),
  static_url('photos/DSCN3533.jpg'),
  static_url('photos/DSCN3535.jpg'),
  static_url('photos/DSCN3536.jpg'),
  static_url('photos/DSCN3557.jpg'),
  static_url('photos/DSCN3559.jpg'),
  static_url('photos/DSCN3580.jpg'),
  static_url('photos/DSCN3588.jpg'),
  static_url('photos/DSCN3685.jpg'),
  static_url('photos/DSCN3688.jpg'),
  static_url('photos/DSCN3692.jpg'),
  static_url('photos/DSCN3710.jpg'),
  static_url('photos/DSCN3725.jpg'),
  static_url('photos/DSCN3726.jpg'),
  static_url('photos/DSCN3729.jpg'),
  static_url('photos/DSCN3731.jpg'),
  static_url('photos/DSCN3734.jpg'),
  static_url('photos/DSCN3742.jpg'),
  static_url('photos/DSCN3753.jpg'),
  static_url('photos/DSCN3755.jpg'),
  static_url('photos/DSCN3758.jpg'),
  static_url('photos/DSCN3763.jpg'),
  static_url('photos/DSCN3774.jpg'),
  static_url('photos/DSCN3807.jpg'),
  static_url('photos/DSCN3901.jpg'),
  static_url('photos/DSCN0005.jpg'),
  static_url('photos/DSCN1063.jpg'),
  static_url('photos/DSCN1068.jpg'),
  static_url('photos/DSCN1076.jpg'),
  static_url('photos/DSCN1083.jpg'),
  static_url('photos/DSCN1084.jpg'),
  static_url('photos/DSCN1099.jpg'),
  static_url('photos/DSCN1180.jpg'),
  static_url('photos/DSCN1279.jpg'),
  static_url('photos/DSCN1316.jpg'),
  static_url('photos/DSCN1332.jpg'),
  static_url('photos/DSCN1338.jpg'),
  static_url('photos/DSCN1359.jpg'),
  static_url('photos/DSCN1360.jpg'),
  static_url('photos/DSCN1368.jpg'),
  static_url('photos/DSCN2939.jpg'),
  static_url('photos/DSCN2945.jpg'),
  static_url('photos/DSCN2958.jpg'),
  static_url('photos/DSCN3059.jpg'),
  static_url('photos/DSCN3077.jpg'),
  static_url('photos/DSCN3094.jpg'),
  static_url('photos/DSCN3099.jpg'),
  static_url('photos/DSCN3104.jpg'),
  static_url('photos/DSCN3107.jpg'),
  static_url('photos/DSCN3120.jpg'),
  static_url('photos/DSCN3145.jpg'),
  static_url('photos/DSCN3159.jpg'),
  static_url('photos/DSCN3167.jpg'),
  static_url('photos/DSCN3191.jpg'),
  static_url('photos/DSCN3193.jpg'),
  static_url('photos/DSCN3195.jpg'),
  static_url('photos/DSCN3219.jpg'),
  static_url('photos/DSCN3240.jpg'),
  static_url('photos/DSCN3241.jpg'),
  static_url('photos/DSCN3486.jpg'),
  static_url('photos/DSCN3490.jpg'),
  static_url('photos/DSCN3491.jpg'),
  static_url('photos/DSCN3492.jpg'),
  static_url('photos/DSCN3494.jpg'),
  static_url('photos/DSCN3495.jpg'),
  static_url('photos/DSCN3498.jpg'),
  static_url('photos/DSCN3500.jpg'),
  static_url('photos/DSCN3503.jpg'),
  static_url('photos/DSCN3513.jpg'),
  static_url('photos/DSCN3520.jpg'),
  static_url('photos/DSCN3533.jpg'),
  static_url('photos/DSCN3535.jpg'),
  static_url('photos/DSCN3536.jpg'),
  static_url('photos/DSCN3557.jpg'),
  static_url('photos/DSCN3559.jpg'),
  static_url('photos/DSCN3580.jpg'),
  static_url('photos/DSCN3588.jpg'),
  static_url('photos/DSCN3685.jpg'),
  static_url('photos/DSCN3688.jpg'),
  static_url('photos/DSCN3692.jpg'),
  static_url('photos/DSCN3710.jpg'),
  static_url('photos/DSCN3725.jpg'),
  static_url('photos/DSCN3726.jpg'),
  static_url('photos/DSCN3729.jpg'),
  static_url('photos/DSCN3731.jpg'),
  static_url('photos/DSCN3734.jpg'),
  static_url('photos/DSCN3742.jpg'),
  static_url('photos/DSCN3753.jpg'),
  static_url('photos/DSCN3755.jpg'),
  static_url('photos/DSCN3758.jpg'),
  static_url('photos/DSCN3763.jpg'),
  static_url('photos/DSCN3774.jpg'),
  static_url('photos/DSCN3807.jpg'),
  static_url('photos/DSCN3901.jpg')] ;
  
  var ret = [];
  var idx = PHOTO_COUNT ;
  while(--idx >= 0) {

    var photoUrlIdx = idx % photoUrls.length ;
    ret[ret.length] = { 
      guid: idx+1, 
      type: 'Photo',
      url: photoUrls[photoUrlIdx],
      name: photoUrls[photoUrlIdx].split('/').last(),
      rotation: 0,
      opacity: 1.0
    } ;
  }
  
  return ret.sort(function(a,b) { return (a.guid < b.guid) ? -1 : ((a.guid > b.guid) ? 1 : 0); }) ;
}());
