// Generated by the WOLips Templateengine Plug-in at 20.11.2009 15:05:59
package your.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
