<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>io.github.wocommunity.wonder.frameworks</groupId>
		<artifactId>plugins</artifactId>
		<version>7.5-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<groupId>io.github.wocommunity.wonder.plugins</groupId>
	<artifactId>mysqlplugin</artifactId>
	<name>MySQLPlugIn</name>

	<dependencies>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-foundation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-eocontrol</artifactId>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-eoaccess</artifactId>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-jdbcadaptor</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.wocommunity.wonder.core</groupId>
			<artifactId>erextensions</artifactId>
		</dependency>
	</dependencies>
</project>