package er.ajax;

// Generated by the WOLips Templateengine Plug-in at Dec 18, 2006 2:21:33 PM

import com.webobjects.appserver.*;

/**
 * Adds a GMarker instance to a Google Map.
 * @author eric robinson
 * @binding id the name of the marker variable, if not specified a unique id is generated automatically.
 * @binding mapID the id used when created AjaxGMap component. The id of the map which the marker is added to.
 * @binding address The address that the marker will be located at. 
 * @binding lng longitude for marker location (must be paired with lat, cannot coexist with address)
 * @binding lat latitude for marker location (must be paired with lng, cannot coexist with address)
 * @binding infoWindowHtml the html that is inside the infowindow
 */
public class AjaxGMarker extends WOComponent {

	private String _id;

	public boolean synchronizesVariablesWithBindings() {
		return false;
	}

	public AjaxGMarker(WOContext context) {
		super(context);
	}

	public String id() {
		if (_id == null) {
			_id = (String) valueForBinding("id");
			if (_id == null) {
				_id = AjaxUtils.toSafeElementID(context().elementID());
			}
		}
		return _id;
	}
}