package er.ajax;
// Generated by the WOLips Templateengine Plug-in at 27.03.2006 21:36:50

import com.webobjects.appserver.*;

public class AjaxUpdateContainer extends AjaxComponent {

    public AjaxUpdateContainer(WOContext context) {
        super(context);
    }
    
    /**
     * Overridden because the component is stateless
     */
    public boolean isStateless() {
        return true;
    }

    /**
     * Overridden because the component does not synch with the bindings.
     */
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }
 
    public String elementName() {
        return (String) valueForBinding("elementName", "span");
    }

    /**
     * Adds all required resources.
     */
    protected void addRequiredWebResources(WOResponse res) {
        addScriptResourceInHead(res, "prototype.js");
        addScriptResourceInHead(res, "scriptaculous.js");
        addScriptResourceInHead(res, "effects.js");
        addScriptResourceInHead(res, "builder.js");
        addScriptResourceInHead(res, "dragdrop.js");
        addScriptResourceInHead(res, "controls.js");
        addScriptResourceInHead(res, "slider.js");
    }
    
    public void appendToResponse(WOResponse _res, WOContext _ctx) {
      super.appendToResponse(_res, _ctx);
      String id = (String)valueForBinding("id");
      _res.appendContentString("<script type = \"text/javascript\" language = \"javascript\"><!--\n");
      _res.appendContentString("function " + id + "Update() { new Ajax.Updater('" + id + "', $(" + id + ").updateUrl, {}); }");
      _res.appendContentString("//--></script>");
    }

    protected WOActionResults handleRequest(WORequest request, WOContext context) {
        WOElement child = _childTemplate();
        WOResponse response = createResponse(context);
        if(child != null) {
            context._setCurrentComponent(parent());
            child.appendToResponse(response, context);
            context._setCurrentComponent(this);
        }
        return response;
    }

}