/*
 *     Generated by class-dump (version 2.1.5).
 *
 *     class-dump is Copyright (C) 1997, 1999, 2000, 2001 by Steve Nygard.
 */

/*
 * File: /System/Library/PrivateFrameworks/PBXCore.framework/PBXCore
 */
#import <Foundation/Foundation.h>
#import <AppKit/AppKit.h>
#define UNKNOWN void
#define NSKeyBinding void
#define FLAGS long
#import "pre.h"
@class PBXDebugThreadViewModule;
@class PBXBuildPhase;
@class PBXBatchBuild;
@class PBXTSTask;
@class PBXFileManager;
@class PBXDSModel;
@class PBXDSDataValue2;
@class PBXDSLaunchSession;
@class PBXDSModulePlugin;
@class PBXThemeButtonImageSource;
@class TSRegularExpression;
@class PBXDSThread;
@class PBXDebugProcessAndThreadModule;
@class TSRegularExpression;
@class PBXBatchFinder;
@class PBXBuildPhasesModule;
@class PBXMethodsList;
@class JKZipFileStore;
@class TSRegularExpression;
@class JKClassLibrary;
@class PBXArchivingBinding;
@protocol PBXTSStreamConsuming
@end
@interface PBXFileManager {}
@end
//#import "/Users/ak/pbxcore.h"
