package er.directtoweb;
// Generated by the WOLips Templateengine Plug-in at 17.12.2006 11:11:36

import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2WCustomComponent;

/**
 * Displays multiple items in one line. Useful for "firstName lastName" stuff.
 * Rules:
 * 100 : .. => displayPropertyKeys = (..., name, ...)
 * 100 : .. and (propertyKey = "name") => displayPropertyKeys = (firstName, lastName)
 * 100 : .. and (propertyKey = "name") => componentName = ERD2WMultiItemCustomComponent
 * Then all firstName and lastName will end up in one line with a "name" label.
 * @author ak
 *
 */
public class ERD2WMultiItemCustomComponent extends D2WCustomComponent {

    public ERD2WMultiItemCustomComponent(WOContext context) {
        super(context);
    }
}