package er.directtoweb;
// Generated by the WOLips Templateengine Plug-in at 08.05.2007 23:51:16

import com.webobjects.appserver.*;

public class ERDDisplayTemplateString extends ERDCustomComponent {

    public ERDDisplayTemplateString(WOContext context) {
        super(context);
    }

    public String templateString() {
        return (String) valueForBinding("templateString");
    }
    
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }
}