package er.directtoweb;
// Generated by the WOLips Templateengine Plug-in at 28.05.2007 11:00:34

import java.util.Enumeration;

import com.webobjects.appserver.WOContext;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.eocontrol.EOEnterpriseObject;

public class ERDHasChangesMarker extends ERDCustomEditComponent {

    public ERDHasChangesMarker(WOContext context) {
        super(context);
    }

    public boolean isStateless() {
        return true;
    }
    
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }
    
    public boolean hasChanges() {
        EOEnterpriseObject object = object();
        EOEditingContext ec = object.editingContext();
        boolean result = ec != null && ec.hasChanges();
        if(result) {
            if(object.changesFromSnapshot(ec.committedSnapshotForObject(object)).count() == 0) {
                for (Enumeration e = ec.registeredObjects().objectEnumerator(); e.hasMoreElements();) {
                    EOEnterpriseObject eo = (EOEnterpriseObject) e.nextElement();
                    if(eo.changesFromSnapshot(ec.committedSnapshotForObject(eo)).count() != 0) {
                        return true;
                    }
                }
                result = false;
            }
        }
        return result;
    }
}