open module org.wocommunity.wonder.erextensions {
	requires java.sql;
	requires java.sql.rowset;
	requires java.naming;
	requires transitive org.wocommunity.webobjects.foundation;
	requires transitive org.wocommunity.webobjects.eocontrol;
	requires transitive org.wocommunity.webobjects.eoaccess;
	requires transitive org.wocommunity.webobjects.webobjects;
	requires transitive org.wocommunity.webobjects.jdbcadaptor;
	requires transitive org.wocommunity.webobjects.woextensions;
	requires transitive org.slf4j;
	requires org.apache.commons.lang3;

	exports er.extensions;
	exports er.extensions.appserver;
	exports er.extensions.appserver.ajax;
	exports er.extensions.appserver.navigation;
	exports er.extensions.batching;
	exports er.extensions.components;
	exports er.extensions.components._private;
	exports er.extensions.components.conditionals;
	exports er.extensions.components.html5;
	exports er.extensions.components.javascript;
	exports er.extensions.components.partials;
	exports er.extensions.concurrency;
	exports er.extensions.crypting;
	exports er.extensions.enums;
	exports er.extensions.eof;
	exports er.extensions.eof.listener;
	exports er.extensions.eof.qualifiers;
	exports er.extensions.formatters;
	exports er.extensions.foundation;
	exports er.extensions.jdbc;
	exports er.extensions.localization;
	exports er.extensions.migration;
	exports er.extensions.net;
	exports er.extensions.partials;
	exports er.extensions.qualifiers;
	exports er.extensions.remoteSynchronizer;
	exports er.extensions.security;
	exports er.extensions.statistics;
	exports er.extensions.statistics.store;
	exports er.extensions.stream;
	exports er.extensions.validation;
	exports er.extensions.virus;
	exports er.extensions.woextensions;
}