package er.directtoweb.components.buttons._ajax;

import com.webobjects.appserver.*;

import er.directtoweb.components.buttons.ERDInspectButton;


// Generated by the WOLips Templateengine Plug-in at May 23, 2008 2:43:01 PM
public class ERDAjaxInspectButton extends ERDInspectButton {
    public ERDAjaxInspectButton(WOContext context) {
        super(context);
    }
}