<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>wonder.frameworks</groupId>
		<artifactId>businesslogic</artifactId>
		<version>7.5-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>wonder.businesslogic</groupId>
	<artifactId>erattachment</artifactId>
	<name>ERAttachment</name>
	<properties>
		<!-- VERY BAD PRACTICE: But there are broken tests -->
		<maven.test.skip>true</maven.test.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>wonder.core</groupId>
			<artifactId>erextensions</artifactId>
		</dependency>
		<dependency>
			<groupId>wonder.core</groupId>
			<artifactId>erprototypes</artifactId>
		</dependency>
		<dependency>
			<groupId>wonder.ajax</groupId>
			<artifactId>ajax</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-foundation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-eocontrol</artifactId>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-eoaccess</artifactId>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-webobjects</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>
	</dependencies>
</project>