package er.directtoweb.components.strings;
// Generated by the WOLips Templateengine Plug-in at 14.05.2007 08:39:52

import com.webobjects.appserver.*;

import er.directtoweb.components.ERDCustomEditComponent;

public class ERDDisplayLargeString extends ERDCustomEditComponent {

    public ERDDisplayLargeString(WOContext context) {
        super(context);
    }

    public boolean synchronizesVariablesWithBindings() {
     	return false;
    }

    public boolean isStateless() {
     	return true;
    }
}