package er.directtoweb.components.dates._ajax;

import com.webobjects.appserver.WOContext;
import er.directtoweb.components.ERDCustomEditComponent;


// Generated by the WOLips Templateengine Plug-in at May 31, 2008 4:09:14 PM
public class ERDAjaxEditDateJavascript extends ERDCustomEditComponent {
    public ERDAjaxEditDateJavascript(WOContext context) {
        super(context);
    }
}