// Generated by the WOLips Templateengine Plug-in at 10.12.2006 15:58:02

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;

import er.extensions.ERXDirectAction;

public class DirectAction extends ERXDirectAction {
    public DirectAction(WORequest aRequest) {
        super(aRequest);
    }

    public WOActionResults defaultAction() {
        return pageWithName(Main.class.getName());
    }
}