package er.ajax;
// Generated by the WOLips Templateengine Plug-in at 25.03.2006 23:08:26

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSMutableDictionary;
/**
 * Simple Ajax slider.
 * @author ak
 *
 */
public class AjaxSlider extends AjaxComponent {

    private String _trackerId;
    private String _handleId;

    public AjaxSlider(WOContext context) {
        super(context);
    }

    /**
     * Overridden because the component is stateless
     */
    public boolean isStateless() {
        return true;
    }

    /**
     * Overridden because the component does not synch with the bindings.
     */
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }

    /**
     * Overridden to add the initialization javascript for the auto completer.
     */
    public void appendToResponse(WOResponse res, WOContext ctx) {
        super.appendToResponse(res, ctx);
        _trackerId = safeElementID() + "_tracker";
        _handleId = safeElementID() + "_handle";
        
        NSMutableDictionary options = new NSMutableDictionary();
        new AjaxOption("axis", AjaxOption.STRING).addToDictionary("orientation", this, options);
        new AjaxOption("sliderValue", AjaxOption.NUMBER).addToDictionary("value", this, options);
        new AjaxOption("onSlide", AjaxOption.SCRIPT).addToDictionary(this, options);
        new AjaxOption("onChange", AjaxOption.SCRIPT).addToDictionary(this, options);
        new AjaxOption("values", AjaxOption.ARRAY).addToDictionary("possibleValues", this, options);
        new AjaxOption("alignX", AjaxOption.NUMBER).addToDictionary(this, options);
        new AjaxOption("alignY", AjaxOption.NUMBER).addToDictionary(this, options);
        new AjaxOption("disabled", AjaxOption.BOOLEAN).addToDictionary(this, options);
        new AjaxOption("handleImage", AjaxOption.STRING).addToDictionary(this, options);
        new AjaxOption("handleDisabled", AjaxOption.STRING).addToDictionary(this, options);

        Number min = (Number)valueForBinding("minimum", new Integer(0));
        Number max = (Number)valueForBinding("maximum", new Integer(100));
        options.setObjectForKey("$R(" + min + "," + max + ")", "range");
        
        res.appendContentString("<div class=\"tracker\" id=\""+
                _trackerId+"\"><div class=\"handle\" id=\""+
                _handleId+"\"></div></div>");
        res.appendContentString("<script type=\"text/javascript\"><!--\n");
        res.appendContentString("new Control.Slider('"+_handleId+"', '"+_trackerId+"', ");
        AjaxOptions.appendToResponse(options, res, ctx);
        res.appendContentString(");");
        res.appendContentString("\n//--></script>");
    }

    /**
     * Adds all required resources.
     */
    protected void addRequiredWebResources(WOResponse res) {
        addScriptResourceInHead(res, "prototype.js");
        addScriptResourceInHead(res, "scriptaculous.js");
        addScriptResourceInHead(res, "effects.js");
        addScriptResourceInHead(res, "builder.js");
        addScriptResourceInHead(res, "dragdrop.js");
        addScriptResourceInHead(res, "controls.js");
        addScriptResourceInHead(res, "slider.js");
    }

    protected WOActionResults handleRequest(WORequest request, WOContext context) {
        return null;
    }

}