package er.ajax;

// Generated by the WOLips Templateengine Plug-in at Apr 28, 2006 9:47:34 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

import er.extensions.ERXStringUtilities;

public class AjaxAccordionTab extends WOComponent {

  public AjaxAccordionTab(WOContext context) {
    super(context);
  }

  public boolean isStateless() {
    return true;
  }

  public boolean synchronizesVariablesWithBindings() {
    return false;
  }

  public String tabID() {
    String id = (String) valueForBinding("id");
    if (id == null) {
      id = ERXStringUtilities.safeIdentifierName(context().elementID()) + "Panel";
    }
    return id;
  }

  public String headerID() {
    return ERXStringUtilities.safeIdentifierName(context().elementID()) + "Header";
  }

  public String contentID() {
    return ERXStringUtilities.safeIdentifierName(context().elementID()) + "Content";
  }
}