package er.ajax;
// Generated by the WOLips Templateengine Plug-in at 25.03.2006 23:08:26

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSArray;
/**
 * Simple Ajax slider.
 * @author ak
 *
 */
public class AjaxSlider extends AjaxComponent {

    private String trackerId;
    private String handleId;

    public AjaxSlider(WOContext context) {
        super(context);
    }

    /**
     * Overridden because the component is stateless
     */
    public boolean isStateless() {
        return true;
    }

    /**
     * Overridden because the component does not synch with the bindings.
     */
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }
 

    public Object valueForBinding(String name, Object defaultValue) {
        Object value = defaultValue;
        if(hasBinding(name)) {
            value = defaultValue;
        }
        return value;
    }
    
    /**
     * Overridden to add the initialization javascript for the auto completer.
     */
    public void appendToResponse(WOResponse res, WOContext ctx) {
        super.appendToResponse(res, ctx);
        trackerId = scriptBaseName() + "_tracker";
        handleId = scriptBaseName() + "_handle";
        
        String orientation = (String) valueForBinding("orientation",  "horizontal");
        Number min = (Number)valueForBinding("minimum", new Integer(0));
        Number max = (Number)valueForBinding("maximum", new Integer(100));
        Number value = (Number)valueForBinding("value", new Integer(0));
        NSArray possibleValues = (NSArray)valueForBinding("possibleValues");
        String onSlide = (String)valueForBinding("onSlide");
        String onChange = (String)valueForBinding("onChange");
        res.appendContentString("<div class=\"tracker\" id=\""+
                trackerId+"\"><div class=\"handle\" id=\""+
                handleId+"\"></div></div>");
        res.appendContentString("<script type=\"text/javascript\"><!--\n"+
                "new Control.Slider('"+handleId+"', '"+trackerId+"', { "+
                "sliderValue:'"+value+"', "+
                "range:$R("+min+ "," +max+ "), "+
                (onSlide != null ? "onSlide: " + onSlide + ", " : "" ) +
                (onChange != null ? "onChange: " + onChange + ", " : "" ) +
                (possibleValues != null ? "values: [" + possibleValues.componentsJoinedByString(",") + "], " : "" ) +
                "axis:'"+orientation+"'"+
                " })"
                +"//--></script>");
    }

    /**
     * Adds all required resources.
     */
    protected void addRequiredWebResources(WOResponse res) {
        addScriptResourceInHead(res, "prototype.js");
        addScriptResourceInHead(res, "scriptaculous.js");
        addScriptResourceInHead(res, "effects.js");
        addScriptResourceInHead(res, "builder.js");
        addScriptResourceInHead(res, "dragdrop.js");
        addScriptResourceInHead(res, "controls.js");
        addScriptResourceInHead(res, "slider.js");
    }

    protected WOActionResults handleRequest(WORequest request, WOContext context) {
        return null;
    }

}