package er.ajax;
// Generated by the WOLips Templateengine Plug-in at 27.03.2006 21:36:50

import com.webobjects.appserver.*;

public class AjaxUpdateContainer extends AjaxComponent {

    public AjaxUpdateContainer(WOContext context) {
        super(context);
    }
    
    /**
     * Overridden because the component is stateless
     */
    public boolean isStateless() {
        return true;
    }

    /**
     * Overridden because the component does not synch with the bindings.
     */
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }
 
    public String elementName() {
        return (String) valueForBinding("elementName", "span");
    }

    /**
     * Adds all required resources.
     */
    protected void addRequiredWebResources(WOResponse res) {
        addScriptResourceInHead(res, "prototype.js");
        addScriptResourceInHead(res, "scriptaculous.js");
        addScriptResourceInHead(res, "effects.js");
        addScriptResourceInHead(res, "builder.js");
        addScriptResourceInHead(res, "dragdrop.js");
        addScriptResourceInHead(res, "controls.js");
        addScriptResourceInHead(res, "slider.js");
    }

    protected WOActionResults handleRequest(WORequest request, WOContext context) {
        WOElement child = _childTemplate();
        WOResponse response = createResponse(context);
        if(child != null) {
            context._setCurrentComponent(parent());
            child.appendToResponse(response, context);
            context._setCurrentComponent(this);
        }
        return response;
    }

}