package er.ajax;
// Generated by the WOLips Templateengine Plug-in at 27.03.2006 21:36:50

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOElement;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSDictionary;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSMutableDictionary;

/**
* observeFieldID requires ERExtensions, specifically ERXWOForm
*/
public class AjaxUpdateContainer extends AjaxComponent {

    public AjaxUpdateContainer(WOContext context) {
        super(context);
    }
    
    /**
     * Overridden because the component is stateless
     */
    public boolean isStateless() {
        return true;
    }

    /**
     * Overridden because the component does not synch with the bindings.
     */
    public boolean synchronizesVariablesWithBindings() {
        return false;
    }
 
    public String elementName() {
        return (String) valueForBinding("elementName", "span");
    }

    /**
     * Adds all required resources.
     */
    protected void addRequiredWebResources(WOResponse res) {
        addScriptResourceInHead(res, "prototype.js");
    }
    
    protected NSDictionary createAjaxOptions() {
      NSMutableArray ajaxOptionsArray = new NSMutableArray();
      ajaxOptionsArray.addObject(new AjaxOption("frequency", AjaxOption.NUMBER));
      ajaxOptionsArray.addObject(new AjaxOption("decay", AjaxOption.NUMBER));
      ajaxOptionsArray.addObject(new AjaxOption("onComplete", AjaxOption.SCRIPT));
      ajaxOptionsArray.addObject(new AjaxOption("onSuccess", AjaxOption.SCRIPT));
      ajaxOptionsArray.addObject(new AjaxOption("onFailure", AjaxOption.SCRIPT));
      ajaxOptionsArray.addObject(new AjaxOption("onException", AjaxOption.SCRIPT));
      ajaxOptionsArray.addObject(new AjaxOption("insertion", AjaxOption.STRING));
      ajaxOptionsArray.addObject(new AjaxOption("evalScripts", AjaxOption.BOOLEAN));
      NSMutableDictionary options = AjaxOption.createAjaxOptionsDictionary(ajaxOptionsArray, this);
      return options;
    }
    
    public String containerID() {
      String id = (String)valueForBinding("id");
      if (id == null) {
        id = AjaxUtils.toSafeElementID(context().elementID());
      }
      return id;
    }
    
    public void appendToResponse(WOResponse _response, WOContext _context) {
      super.appendToResponse(_response, _context);
      String id = containerID();
      
      NSDictionary options = createAjaxOptions();
      
      _response.appendContentString("<script type = \"text/javascript\" language = \"javascript\"><!--\n");
      if (canGetValueForBinding("frequency")) {
        _response.appendContentString("new Ajax.PeriodicalUpdater('" + id + "', $(" + id + ").updateUrl, ");
        AjaxOptions.appendToResponse(options, _response, _context);
        _response.appendContentString(");");
      }
      
      if (canGetValueForBinding("observeFieldID")) {
        String observeFieldID = (String)valueForBinding("observeFieldID");
        _response.appendContentString("new Form.Element.Observer($('" + observeFieldID + "'), 1, function(element, value) {");
        NSMutableDictionary observerOptions = new NSMutableDictionary();
        observerOptions.setObjectForKey("true", "asynchronous");
        
        // We need to cheat and make the WOForm that contains the form action appear to have been
        // submitted.  So we grab the action url, pull off the element ID from its action URL
        // and pass that in as FORCE_FORM_SUBMITTED_KEY, which is processed by ERXWOForm just like
        // senderID is on the real WOForm.  Unfortunately we can't hook into the real WOForm to do
        // this :(
        _response.appendContentString("var formAction = $('" + observeFieldID + "').form.action;");
        _response.appendContentString("var senderID = formAction.substring(formAction.indexOf('.', formAction.lastIndexOf('/')) + 1);");
        StringBuffer parameters = new StringBuffer();
        parameters.append("escape($('" + observeFieldID + "').name) + '=' + escape($('" + observeFieldID + "').value) + '");
        parameters.append("&");
        parameters.append(AjaxUtils.FORCE_FORM_SUBMITTED_KEY + "=' + senderID + '");
        parameters.append("'");
        
        observerOptions.setObjectForKey(parameters.toString(), "parameters");
        _response.appendContentString("new Ajax.Updater('" + id + "', $('" + id + "').updateUrl, ");
        AjaxOptions.appendToResponse(observerOptions, _response, _context);
        _response.appendContentString(") });");
      }

      _response.appendContentString("function " + id + "Update() { new Ajax.Updater('" + id + "', $(" + id + ").updateUrl, ");
      AjaxOptions.appendToResponse(options, _response, _context);
      _response.appendContentString("); }");
      
      _response.appendContentString("//--></script>");
    }

    protected WOActionResults handleRequest(WORequest request, WOContext context) {
        WOElement child = _childTemplate();
        WOResponse response = AjaxUtils.createResponse(context);
        AjaxUtils.setPageReplacementCacheKey(context, containerID());
        context.appendZeroElementIDComponent();
        if (child != null) {
            context._setCurrentComponent(parent());
            child.appendToResponse(response, context);
            context._setCurrentComponent(this);
        }
        return response;
    }

}