package er.ajax;
// Generated by the WOLips Templateengine Plug-in at 03.04.2007 12:08:59

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOElement;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSDictionary;

/**
 * Hints input and textarea fields with ghosted text that serves as an explainatation for the user what to enter.
 * The style "ajax-hinted-text-with-default" defines the color for this.
 * 
 * @binding form ID of the form to apply the hints to
 * @author ak
 */

public class AjaxTextHinter extends AjaxDynamicElement {

	public AjaxTextHinter(String name, NSDictionary associations, WOElement children) {
		super(name, associations, children);
	}

	public WOActionResults handleRequest(WORequest request, WOContext context) {
		return null;
	}

	protected void addRequiredWebResources(WOResponse response, WOContext context) {
		addScriptResourceInHead(context, response, "prototype.js");
		addScriptResourceInHead(context, response, "behaviour.js");
		addScriptResourceInHead(context, response, "wonder.js");
	}
	
	public void appendToResponse(WOResponse response, WOContext context) {
		super.appendToResponse(response, context);
		String name = (String) valueForBinding("form", context.component());
		if(name != null) {
			name = "'" + name + "'";
		} else {
			name = "";
		}
		response.appendContentString("<script>AjaxHintedText.register(" + name + ")</script>");
	}

}