// Generated by the WOLips Templateengine Plug-in at Oct 1, 2006 4:22:04 PM

import com.webobjects.appserver.*;

public class PanelExample extends WOComponent {

    public PanelExample(WOContext context) {
        super(context);
    }

}