package er.ajax.look.pages;
//Generated by the WOLips Templateengine Plug-in at 12.02.2007 19:53:50

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;

import er.directtoweb.pages.ERD2WListPage;
import er.yui.YUIUtils;

public class AjaxLookListPage extends ERD2WListPage {
	/**
	 * Do I need to update serialVersionUID?
	 * See section 5.6 <cite>Type Changes Affecting Serialization</cite> on page 51 of the 
	 * <a href="http://java.sun.com/j2se/1.4/pdf/serial-spec.pdf">Java Object Serialization Spec</a>
	 */
	private static final long serialVersionUID = 1L;

    public AjaxLookListPage(WOContext context) {
        super(context);
    }

    public void appendToResponse(WOResponse response, WOContext context) {

        super.appendToResponse(response, context);

        YUIUtils.addScriptResourceInHead(context, response, "yahoo/yahoo.js");
        YUIUtils.addScriptResourceInHead(context, response, "dom/dom.js");
        YUIUtils.addScriptResourceInHead(context, response, "event/event.js");
        YUIUtils.addScriptResourceInHead(context, response, "animation/animation.js");
        YUIUtils.addScriptResourceInHead(context, response, "dragdrop/dragdrop.js");
        YUIUtils.addScriptResourceInHead(context, response, "container/container.js");
        YUIUtils.addScriptResourceInHead(context, response, "ext/yui-ext.js");
        YUIUtils.addScriptResourceInHead(context, response, "wonder.js");
        YUIUtils.addStylesheetResourceInHead(context, response, "container/assets/container.css");
        YUIUtils.addStylesheetResourceInHead(context, response, "ext/resources/css/grid.css");
    }
    
    public String containerID() {
    	return new StringBuilder().append(d2wContext().dynamicPage()).append("Grid").toString();
    }
}