package er.directtoweb.components.buttons._xhtml;

import com.webobjects.appserver.*;

import er.directtoweb.components.buttons.ERDInspectButton;


// Generated by the WOLips Templateengine Plug-in at May 23, 2008 2:43:01 PM
public class ERDInspectButton2 extends ERDInspectButton {
    public ERDInspectButton2(WOContext context) {
        super(context);
    }
}