package com.webobjects.directtoweb._xhtml;

import com.webobjects.appserver.*;
import com.webobjects.directtoweb.D2WDisplayToManyTable;

// Generated by the WOLips Templateengine Plug-in at Jun 17, 2008 5:38:29 PM
public class D2WDisplayToManyList extends D2WDisplayToManyTable {
    public D2WDisplayToManyList(WOContext context) {
        super(context);
    }
    
    // accessors
    public boolean hasItems() {
    	return (list().count() > 0);
    }
}