package er.diva.components.repetitions;

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.repetitions.ERDInspectPageRepetition;
import er.extensions.foundation.ERXStringUtilities;
import er.extensions.foundation.ERXValueUtilities;

// Generated by the WOLips Templateengine Plug-in at Aug 11, 2008 10:46:25 AM
public class ERDIVEditPageRepetition extends ERDInspectPageRepetition {
    public ERDIVEditPageRepetition(WOContext context) {
        super(context);
    }
    
    // accessors	
    //FIXME RM: move into rules
	public String propertyClassString() {
		return isMandatory() ? "propertyKey mandatory" : "propertyKey";
	}
	
	public boolean isMandatory() {
		Object b = d2wContext().valueForKey("isMandatory");
		return b != null ? ERXValueUtilities.booleanValue(b) : false;
	}
	
    //FIXME RM: move into rules
	public String contentClassString() {
		return "content " + d2wContext().componentName();
	}
	
	public boolean disabled() {
		return !hasSections();
	}
	
	public String attributeClassString() {
		String attributeClassString = (String) d2wContext().valueForKey("classForAttribute");
		return hasTitle() ? attributeClassString + " tooltip" : attributeClassString;
	}
	
	private String title() {
		return (String) d2wContext().valueForKey("title");
	}
	
	private boolean hasTitle() {
		return (title() != null && !title().equals(""));
	}
	
	public String contentContainerID() {
		return d2wContext().valueForKey("id") + "_container";
	}
}