// Generated by the WebObjects Wizard Tue Jun 06 12:54:36 US/Eastern 2000

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;

public class LogoutPage extends VacationComponent {

    public LogoutPage(WOContext context) {
        super(context);
    }

}
