// Generated by the WebObjects Wizard Thu Oct 18 13:46:09 GMT 2001

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;

public class SettingsPage extends VacationComponent {
    protected Setting setting;
    protected String newYear;

    public SettingsPage(WOContext context) {
        super(context);

        if ((setting = Setting.currentSettingForContext(session.defaultEditingContext())) == null)
        {
            System.out.println ("creating new setting");
            setting = new Setting();
            session().defaultEditingContext().insertObject(setting);
        }
    }

    public WOComponent saveChanges() {
        try {
            session().defaultEditingContext().saveChanges();
            this.setMessage("Changes saved");
        }
        catch (Exception e) {
            this.setMessage(e.getMessage());
        }
        return null;
    }

    public WOComponent cancel() {
        session().defaultEditingContext().invalidateAllObjects();
        return pageWithName("PersonSummary");
    }
    
    public WOComponent createNewYear() {
        if (newYear!=null) {
            Integer numberYear = new Integer(newYear);
            // fetch all users
            NSArray users = EOUtilities.objectsForEntityNamed(session.defaultEditingContext(), "Person");
            java.util.Enumeration enumerator = users.objectEnumerator();

            while (enumerator.hasMoreElements()) {
                Person ePerson = (Person) enumerator.nextElement();

                YearlyData newYearlyData = new YearlyData(numberYear);
                session.defaultEditingContext().insertObject(newYearlyData);

                ePerson.addToYearlyData(newYearlyData);
            }

            try {
                session.defaultEditingContext().saveChanges();
                ((Application) application()).yearsCache = null;
            }
            catch (Exception e) {
                this.setMessage(e.getMessage());
            }

        }
        return null;
    }
}
