// Generated by the WOLips Templateengine Plug-in at Mar 26, 2007 1:35:12 PM

import com.webobjects.appserver.*;

public class AjaxTabbedPanelDemo extends WOComponent {

    public AjaxTabbedPanelDemo(WOContext context) {
        super(context);
    }

}