// Generated by the WOLips Templateengine Plug-in at Apr 22, 2006 10:12:27 AM

import com.webobjects.appserver.*;

public class DragAndDropExample extends WOComponent {

  public DragAndDropExample(WOContext _context) {
    super(_context);
  }

}