// Generated by the WOLips Templateengine Plug-in at Apr 1, 2007 7:20:22 PM

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;

import er.ajax.AjaxHighlight;

public class HighlightExample extends WOComponent {
	private NSMutableArray _comments;
	private Comment _comment;
	public Comment _repetitionComment;
	
	public HighlightExample(WOContext context) {
		super(context);
		_comments = new NSMutableArray();
		for (int i = 1; i < 4; i ++) {
			Comment comment = new Comment();
			comment.setText("This is comment #" + i);
			_comments.addObject(comment);
		}
	}
	
	public NSArray comments() {
		return _comments;
	}
	
	public Comment comment() {
		if (_comment == null) {
			_comment = new Comment();
		}
		return _comment;
	}
	
	public WOActionResults save() {
		AjaxHighlight.highlight(_comment);
		_comments.addObject(_comment);
		_comment = null;
		return null;
	}

	public static class Comment {
		private String _text;

		public Comment() {
		}
		
		public void setText(String text) {
			_text = text;
		}

		public String text() {
			return _text;
		}
	}
}