// Generated by the WOLips Templateengine Plug-in at Sep 21, 2006 9:19:23 PM

import com.webobjects.appserver.*;

public class LinkExample extends WOComponent {
  private boolean _showingSubComponent1;

  public LinkExample(WOContext context) {
    super(context);
    _showingSubComponent1 = true;
  }

  public WOActionResults exampleAction() {
    System.out.println("LinkExample.exampleAction: Action Performed!");
    return null;
  }
  
  public String now() {
	  return String.valueOf(System.currentTimeMillis());
  }

  public WOActionResults replaceLinkAction() {
    WOActionResults results;
    if (_showingSubComponent1) {
      results = pageWithName(LinkExampleSubComponent2.class.getName());
    }
    else {
      results = pageWithName(LinkExampleSubComponent1.class.getName());
    }
    _showingSubComponent1 = !_showingSubComponent1;
    return results;
  }
}