// Generated by the WOLips Templateengine Plug-in at 09.03.2006 16:24:23

import com.webobjects.appserver.*;

 import com.metaparadigm.dict.DictClient;

public class Main extends WOComponent {
    
    private int counter = 0;
    private DictClient dict;
    
    public Main(WOContext context) {
        super(context);
    }
    
    public int addMore(int x) {
        return counter = counter + x;
    }
    
    public int add() {
        return ++counter;
    }
    
    public DictClient dict() {
        if (dict == null) {
            dict = new DictClient("dict.die.net");
        }
        return dict;
    }
    
}