// Generated by the WOLips Templateengine Plug-in at Mar 26, 2007 4:26:08 PM

import com.webobjects.appserver.*;

public class SlowLoadingComponent extends WOComponent {

    public SlowLoadingComponent(WOContext context) {
        super(context);
    }

	public void appendToResponse(WOResponse aResponse, WOContext aContext) {
		try {
			Thread.sleep(5000);
		}
		catch (InterruptedException e) {
		}
		super.appendToResponse(aResponse, aContext);
	}

}