<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.wocommunity.wonder.frameworks</groupId>
		<artifactId>frameworks</artifactId>
		<version>8.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>core</artifactId>
	<packaging>pom</packaging>
	<name>Core Frameworks</name>
	<description>Project Wonder: A collection of frameworks designed for use with WebObjects.</description>
	<url>https://wocommunity.org</url>

	<organization>
		<name>WOCommunity</name>
		<url>http://www.wocommunity.org/</url>
	</organization>

	<licenses>
		<license>
			<name>NetStruxr Public Software License</name>
			<url>https://github.com/wocommunity/wonder/blob/master/Frameworks/Core/ERExtensions/Documentation/LICENSE.NPL</url>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>Ramsey Gurley</name>
			<email>ramseygurley@gmail.com</email>
			<organization>WOCommunity</organization>
			<organizationUrl>https://github.com/wocommunity/</organizationUrl>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:https://github.com/wocommunity/wonder.git</connection>
		<url>scm:git:https://github.com/wocommunity/wonder.git</url>
		<developerConnection>scm:git:https://github.com/wocommunity/wonder.git</developerConnection>
		<tag>HEAD</tag>
	</scm>
	<modules>
		<module>ERDirectToWeb</module>
		<module>ERExtensions</module>
		<module>ERJavaMail</module>
		<module>ERNeutralLook</module>
		<module>ERPrototypes</module>
		<module>JavaWOExtensions</module>
	</modules>
</project>