package er.restexample.server;
// Generated by the WOLips Templateengine Plug-in at 04.03.2009 23:02:26

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
    
	public Session() {
	    
	}
	
	public boolean isLoggedIn() {
	    return true;
	}
}