/* Generated By:JavaCC: Do not edit this line. GSVUtilityParserConstants.java */
package com.gammastream.validity._private;

public interface GSVUtilityParserConstants {

  int EOF = 0;
  int email_address = 1;
  int word = 2;
  int url = 3;
  int login = 4;
  int hostport = 5;
  int host = 6;
  int hostname = 7;
  int domainlabel = 8;
  int toplabel = 9;
  int alphadigit = 10;
  int hostnumber = 11;
  int port = 12;
  int user = 13;
  int password = 14;
  int urlpath = 15;
  int ftp_url = 16;
  int fpath = 17;
  int fsegment = 18;
  int ftptype = 19;
  int file_url = 20;
  int http_url = 21;
  int hpath = 22;
  int hsegment = 23;
  int search = 24;
  int https_url = 25;
  int gopher_url = 26;
  int gtype = 27;
  int selector = 28;
  int gopher_and_string = 29;
  int mailto_url = 30;
  int encoded822addr = 31;
  int news_url = 32;
  int grouppart = 33;
  int group = 34;
  int article = 35;
  int telnet_url = 36;
  int lowalpha = 37;
  int hialpha = 38;
  int alpha = 39;
  int digit = 40;
  int safe = 41;
  int extra = 42;
  int national = 43;
  int punctuation = 44;
  int reserved = 45;
  int hex = 46;
  int escape = 47;
  int unreserved = 48;
  int uchar = 49;
  int xchar = 50;
  int digits = 51;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<email_address>",
    "<word>",
    "<url>",
    "<login>",
    "<hostport>",
    "<host>",
    "<hostname>",
    "<domainlabel>",
    "<toplabel>",
    "<alphadigit>",
    "<hostnumber>",
    "<port>",
    "<user>",
    "<password>",
    "<urlpath>",
    "<ftp_url>",
    "<fpath>",
    "<fsegment>",
    "<ftptype>",
    "<file_url>",
    "<http_url>",
    "<hpath>",
    "<hsegment>",
    "<search>",
    "<https_url>",
    "<gopher_url>",
    "<gtype>",
    "<selector>",
    "<gopher_and_string>",
    "<mailto_url>",
    "<encoded822addr>",
    "<news_url>",
    "<grouppart>",
    "<group>",
    "<article>",
    "<telnet_url>",
    "<lowalpha>",
    "<hialpha>",
    "<alpha>",
    "<digit>",
    "<safe>",
    "<extra>",
    "<national>",
    "<punctuation>",
    "<reserved>",
    "<hex>",
    "<escape>",
    "<unreserved>",
    "<uchar>",
    "<xchar>",
    "<digits>",
  };

}
