package er.corebusinesslogic;
// Generated by the WOLips Templateengine Plug-in at 17.09.2006 22:39:35

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2W;
import com.webobjects.directtoweb.EditPageInterface;
import com.webobjects.eocontrol.EOEnterpriseObject;

import er.extensions.ERXEOControlUtilities;
import er.extensions.ERXStatelessComponent;

public class ERCDisplayHelpText extends ERXStatelessComponent {

    public ERCDisplayHelpText(WOContext context) {
        super(context);
    }

    public ERCHelpText helpText() {
    	return ERCHelpText.clazz.helpTextForKey(session().defaultEditingContext(), key());
    }

    public boolean showCreate() {
    	return showActions() && helpText() == null;
    }

    public boolean showEdit() {
    	return showActions() && helpText() != null;
    }
    
    public boolean showActions() {
    	return true;
    }
    
	private String key() {
		return (String) valueForBinding("key");
	}
	
	public WOComponent createHelpText() {
		EditPageInterface page = D2W.factory().editPageForNewObjectWithEntityNamed(ERCHelpText.ENTITY, session());
		((WOComponent) page).takeValueForKeyPath(key(), "object." + ERCHelpText.Key.KEY);
		page.setNextPage(context().page());
		return (WOComponent) page;
	}
	
	public WOComponent editHelpText() {
		EditPageInterface page = D2W.factory().editPageForEntityNamed(ERCHelpText.ENTITY, session());
		EOEnterpriseObject eo = ERXEOControlUtilities.editableInstanceOfObject(helpText(), false);
		page.setObject(eo);
		page.setNextPage(context().page());
		return (WOComponent) page;
	}
}