package er.corebusinesslogic;
// Generated by the WOLips Templateengine Plug-in at 12.05.2007 04:24:08

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2W;
import com.webobjects.directtoweb.EditPageInterface;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.foundation.NSArray;

import er.extensions.ERXEC;

public class ERCListHelpText extends WOComponent {

	public String key;
	
    public ERCListHelpText(WOContext context) {
        super(context);
    }
    
    public boolean showList() {
    	return true;
    }
    
    public void setShowList(boolean value) {
    }
    
    public ERCHelpText text() {
    	return ERCHelpText.clazz.helpTextForKey(session().defaultEditingContext(), key);
    } 
    
    public WOComponent edit() {
       	EOEditingContext ec = ERXEC.newEditingContext();
       	ec.lock();
       	try {
       		ERCHelpText text = ERCHelpText.clazz.helpTextForKey(ec, key);
       		if(text == null) {
       			text = (ERCHelpText) ERCHelpText.clazz.createAndInsertObject(ec);
       			text.setKey(key);
       		}
       		EditPageInterface page = D2W.factory().editPageForEntityNamed(ERCHelpText.ENTITY, session());
       		page.setObject(text);
       		page.setNextPage(context().page());
       		return (WOComponent)page;
       	} finally {
       		ec.unlock();
       	}
    }
    
    public NSArray keys() {
		return ERCDisplayHelpText.textsOnPage();
    }

}