package er.reporting.examples;

import er.grouping.*;
import er.reporting.*;
import java.lang.*;
import java.util.*;
import java.io.*;
import com.webobjects.foundation.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;
import com.webobjects.appserver.*;
import er.extensions.appserver.ERXSession;

// Generated by the WebObjects Wizard
public class Session extends ERXSession  {

    public DRReportModel model;
    public NSArray attribArray;
    public NSArray critArray;
    public boolean reportEditor;

    // Generated by the WebObjects Wizard
    public Session() {
        super();
        //[self setTimeOut:10];
        reportEditor = false;
        Class arrClass [] = {NSNotification.class};
        NSNotificationCenter.defaultCenter().addObserver(this, new NSSelector("synchModel", arrClass), "DRReportModelUpdate", null);
        return;
    }


    public DRReportModel model() {
        return model;
    }
    public void setModel(DRReportModel amodel) {
        model = amodel;
    }


    public void synchModel(NSNotification not) {
        NSLog.out.appendln("Session: synchModel: notification: "+(not));
        if(this.model() != null)
        this.model().setAttributeList(attribArray);
    }


}