<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>io.github.wocommunity.wonder.frameworks</groupId>
		<artifactId>eof</artifactId>
		<version>8.0.0</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>io.github.wocommunity.wonder.eof</groupId>
	<artifactId>erjgroupssynchronizer</artifactId>
	<name>ERJGroupsSynchronizer</name>
	<description>Project Wonder: A collection of frameworks designed for use with WebObjects.</description>
	<url>https://wocommunity.org</url>

	<organization>
		<name>WOCommunity</name>
		<url>http://www.wocommunity.org/</url>
	</organization>

	<licenses>
		<license>
			<name>NetStruxr Public Software License</name>
			<url>https://github.com/wocommunity/wonder/blob/master/Frameworks/Core/ERExtensions/Documentation/LICENSE.NPL</url>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>Ramsey Gurley</name>
			<email>ramseygurley@gmail.com</email>
			<organization>WOCommunity</organization>
			<organizationUrl>https://github.com/wocommunity/</organizationUrl>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:https://github.com/wocommunity/wonder.git</connection>
		<url>scm:git:https://github.com/wocommunity/wonder.git</url>
		<developerConnection>scm:git:https://github.com/wocommunity/wonder.git</developerConnection>
		<tag>wonder-8.0.0</tag>
	</scm>
	<dependencies>
		<dependency>
			<groupId>io.github.wocommunity.wonder.core</groupId>
			<artifactId>erextensions</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jgroups</groupId>
			<artifactId>jgroups</artifactId>
		</dependency>
	</dependencies>
</project>