package er.bugtracker;
// Generated by the WOLips Templateengine Plug-in at 07.05.2007 11:20:49

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERDCustomComponent;

public class PageHeader extends ERDCustomComponent {

    public PageHeader(WOContext context) {
        super(context);
    }
    
    public boolean synchronizesVariablesWithBindings() {
    	return false;
    }
}