package er.ajax.look.pages;
//Generated by the WOLips Templateengine Plug-in at 12.02.2007 19:53:50

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;

import er.directtoweb.ERD2WListPage;
import er.yui.YUIUtils;

public class AjaxLookListPage extends ERD2WListPage {

    public AjaxLookListPage(WOContext context) {
        super(context);
    }

    public void appendToResponse(WOResponse response, WOContext context) {

        super.appendToResponse(response, context);

        YUIUtils.addScriptResourceInHead(context, response, "yahoo/yahoo.js");
        YUIUtils.addScriptResourceInHead(context, response, "dom/dom.js");
        YUIUtils.addScriptResourceInHead(context, response, "event/event.js");
        YUIUtils.addScriptResourceInHead(context, response, "animation/animation.js");
        YUIUtils.addScriptResourceInHead(context, response, "dragdrop/dragdrop.js");
        YUIUtils.addScriptResourceInHead(context, response, "container/container.js");
        YUIUtils.addScriptResourceInHead(context, response, "ext/yui-ext.js");
        YUIUtils.addScriptResourceInHead(context, response, "wonder.js");
        YUIUtils.addStylesheetResourceInHead(context, response, "container/assets/container.css");
        YUIUtils.addStylesheetResourceInHead(context, response, "ext/resources/css/grid.css");
    }
}