// Generated by the WOLips Templateengine Plug-in at 12.02.2007 19:52:49

import com.webobjects.appserver.*;

public class PageWrapper extends WOComponent {

    public PageWrapper(WOContext context) {
        super(context);
    }

}