// Generated by the WebObjects Wizard Thu Nov 02 10:30:57 US/Pacific 2000

import com.webobjects.foundation.*;
import com.webobjects.directtoweb.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;
import demo.eo.*;

public class LinkToViewMovie2 extends WOComponent {

    public LinkToViewMovie2(WOContext aContext) {
        super(aContext);
    }

    public boolean isStateless() { return true; }

    public EOEnterpriseObject object() { return (EOEnterpriseObject)valueForBinding("object"); }
    public String key() { return (String)valueForBinding("key"); }

    public Movie movie() {
        return (Movie)(object() instanceof Movie ? object() : object().valueForKeyPath(key()));
    }

    public WOComponent view() {
        InspectPageInterface ipi = (InspectPageInterface)D2W.factory().pageForConfigurationNamed("InspectMovie1", session());
        ipi.setObject(movie());
        ipi.setNextPage(context().page());
        return (WOComponent)ipi;
    }
}
