package er.iui.example.components;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Mar 7, 2008 10:43:33 PM
public class Main2 extends ERXComponent {
  public boolean _searchVisible;

  public Main2(WOContext context) {
    super(context);
  }

  public WOActionResults something() {
    System.out.println("Main.something: Going to Main");
    return pageWithName(Main.class);
  }

  public WOActionResults back() {
    System.out.println("Main2.back: BACK");
    return pageWithName(Main.class);
  }

  public WOActionResults search() {
    _searchVisible = false;
    System.out.println("Main2.search: SEARCH");
    return null;
  }

  public WOActionResults cancel() {
    _searchVisible = false;
    return null;
  }
}