package er.iui.example.components;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Apr 2, 2008 11:05:58 PM
public class Prefs extends ERXComponent {
  private boolean _repeat;
  private boolean _shuffle;
  private String _userName;
  private String _password;
  private String _passwordConfirm;

  public Prefs(WOContext context) {
    super(context);
    _repeat = true;
  }

  /**
   * @return the repeat
   */
  public boolean repeat() {
    return _repeat;
  }

  /**
   * @param repeat the repeat to set
   */
  public void setRepeat(boolean repeat) {
    System.out.println("Prefs.setRepeat: " + _repeat);
    _repeat = repeat;
  }

  /**
   * @return the shuffle
   */
  public boolean shuffle() {
    return _shuffle;
  }

  /**
   * @param shuffle the shuffle to set
   */
  public void setShuffle(boolean shuffle) {
    _shuffle = shuffle;
  }

  /**
   * @return the userName
   */
  public String userName() {
    return _userName;
  }

  /**
   * @param userName the userName to set
   */
  public void setUserName(String userName) {
    _userName = userName;
  }

  /**
   * @return the password
   */
  public String password() {
    return _password;
  }

  /**
   * @param password the password to set
   */
  public void setPassword(String password) {
    _password = password;
  }

  /**
   * @return the passwordConfirm
   */
  public String passwordConfirm() {
    return _passwordConfirm;
  }

  /**
   * @param passwordConfirm the passwordConfirm to set
   */
  public void setPasswordConfirm(String passwordConfirm) {
    _passwordConfirm = passwordConfirm;
  }

  public WOActionResults done() {
    System.out.println("Prefs.done: " + _repeat + ", " + _shuffle + ", " + _userName + ", " + _password);
    return pageWithName(Main.class);
  }

  public WOActionResults doSomething() {
    System.out.println("Prefs.doSomething: " + _shuffle + ", " + _repeat + ", " + _userName + ", " + _password);
    return null;
  }

  public WOActionResults main() {
    return pageWithName(Main.class);
  }
}