// Generated by the WOLips Templateengine Plug-in at Apr 22, 2007 10:18:57 AM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {

  public Main(WOContext context) {
    super(context);
  }

}