<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>wonder.frameworks</groupId>
		<artifactId>misc</artifactId>
		<version>7.5-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<groupId>wonder.core</groupId>
	<artifactId>erpdfgeneration</artifactId>
	<name>ERPDFGeneration</name>
	<dependencies>
		<dependency>
			<groupId>wonder.core</groupId>
			<artifactId>erextensions</artifactId>
		</dependency>
		<dependency>
			<groupId>org.xhtmlrenderer</groupId>
			<artifactId>flying-saucer-pdf</artifactId>
		</dependency>
		<dependency>
			<groupId>com.github.librepdf</groupId>
			<artifactId>openpdf</artifactId>
		</dependency>
		<dependency>
			<groupId>net.sf.ujac</groupId>
			<artifactId>ujac</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlgraphics</groupId>
			<artifactId>xmlgraphics-commons</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlgraphics</groupId>
			<artifactId>fop</artifactId>
		</dependency>
	</dependencies>
</project>