package er.directtoweb.components.bool._xhtml;

import com.webobjects.appserver.*;

import er.directtoweb.components.bool.ERD2WCustomQueryBoolean;

// Generated by the WOLips Templateengine Plug-in at Aug 4, 2008 3:34:46 PM
public class ERD2WQueryBooleanRadioList extends ERD2WCustomQueryBoolean {
    public ERD2WQueryBooleanRadioList(WOContext context) {
        super(context);
    }
}