// Generated by the WebObjects Wizard

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;

public class Application extends WOApplication { 

public static void main(String argv[]) {
        WOApplication.main(argv, Application.class);
    }

    public Application() {
        System.out.println("Welcome to " + this.name() + " !");
    }
}
