// Generated by the WOLips Templateengine Plug-in at Mar 7, 2008 10:03:32 PM
package er.iui.example;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
  private static final long serialVersionUID = 1L;

  public Session() {
  }
}
