package er.bugtracker;
// Generated by the WOLips Templateengine Plug-in at 07.05.2007 11:20:49

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERDCustomComponent;

/**
 * Simple display of some info on the top of the page.
 * @author ak
 *
 */
public class PageHeader extends ERDCustomComponent {

    public PageHeader(WOContext context) {
        super(context);
    }
    
    public String explaination() {
        return valueForBinding("pageConfiguration") + ".explaination";
    }
    
    public String header() {
        return (String) valueForBinding("displayNameForPageConfiguration");
    }
    
    public boolean synchronizesVariablesWithBindings() {
    	return false;
    }
}