package er.divalite.example;

// Generated by the WOLips Templateengine Plug-in at May 22, 2008 5:06:36 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.foundation.NSArray;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
	private int i = 0;
	private NSArray<String> themes = new NSArray<String>(new String[]{"Neutral", "WebObjects", "Modern"});
	
	public Session() {
	}
	
	// actions
	public WOComponent toggleLook() {
		i = (i+1)%3;
		return null;
	}

    // accessors
    public String theme() {
    	return themes.get(i);
    }

	public boolean isWebObjectsTheme() {
		return theme().equals("WebObjects");
	}
	
	public boolean isModernTheme() {
		return theme().equals("Modern");
	}
}