#!/bin/bash
 
# chkconfig: - 90 20
# description: Provides JavaMonitor service
 
# Source function library.
. /etc/rc.d/init.d/functions
 
NEXT_ROOT="/opt"
export NEXT_ROOT
 
PATH="/bin:/usr/bin:/usr/java/latest/bin"
export PATH
 
USER=appserver
 
# See how we were called.
case "$1" in
    start)
        echo -n "Starting JavaMonitor: "
		su $USER -c "$NEXT_ROOT/Local/Library/WebObjects/JavaApplications/JavaMonitor.woa/JavaMonitor -WOPort 56789 &"
        echo
        ;;
    stop)
		echo -n "Shutting down JavaMonitor: "
		MONITOR_PID=`ps aux | awk '/WOPort 56789/ && !/awk/ {print $2}'`
		kill $MONITOR_PID
        echo
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo -n "Usage: $0 {start|stop|restart}"
        exit 1
esac
 
if [ $# -gt 1 ]; then
    shift
    $0 $*
fi
 
exit 0