// Generated by the WOLips Templateengine Plug-in at Apr 12, 2008 12:11:06 PM
package er.restadaptorexample;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
