package er.divalite.example;

// Generated by the WOLips Templateengine Plug-in at May 22, 2008 5:06:36 PM

import com.webobjects.appserver.WOComponent;
import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
	private boolean isWebObjectsTheme = false;
	
	public Session() {
	}
	
	// actions
	public WOComponent toggleLook() {
		isWebObjectsTheme = !isWebObjectsTheme;
		return null;
	}

    // accessors
    public String theme() {
    	return isWebObjectsTheme ? "WebObjects" : "Neutral";
    }

	public boolean isWebObjectsTheme() {
		return isWebObjectsTheme;
	}
}