package er.directtoweb.components.repetitions;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at 11.02.2008 21:03:31
/**
 * @d2wKey object
 */
public class ERDTableRepetition extends ERDListPageRepetition {
    public ERDTableRepetition(WOContext context) {
        super(context);
    }
}