package er.directtoweb.components.relationships._xhtml;

import com.webobjects.appserver.*;
import er.directtoweb.components.relationships.ERD2WQueryToOneRelationship;

// Generated by the WOLips Templateengine Plug-in at Aug 5, 2008 1:06:21 PM
public class ERD2WQueryToOneRelationship2 extends ERD2WQueryToOneRelationship {
    public ERD2WQueryToOneRelationship2(WOContext context) {
        super(context);
    }
    // accessors
    @Override
    public String componentName() {
        return !hasMultipleSelection() ? "ERXToOneRelationship2" :  "ERXToManyRelationship2";
    }
}