NSProjectSearchPath=(/Volumes/Home/Wonder/Common/Applications)
WOPort=2002
WODocumentRoot=/Volumes/Home/Sites/web
dbConnectURLGLOBAL=jdbc:postgresql://localhost/bug
dbConnectUserGLOBAL=ak
dbConnectPluginGLOBAL=Postgresql
dbConnectDriverGLOBAL=org.postgresql.Driver
dbEOPrototypesEntityGLOBAL=EOJDBCPostgresqlPrototypes
er.javamail.adminEmail=foo@localhost.com

BugTracker.processMail=false
BugTracker.mailStore=pop3
BugTracker.server=localhost
BugTracker.user=ak
BugTracker.password=
