package er.erxtest;
// Generated by the WOLips Templateengine Plug-in at Jan 24, 2007 2:11:22 AM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {

    public Main(WOContext context) {
        super(context);
    }

}