// Generated by the WebObjects Wizard Sun Apr 04 22:59:37 US/Central 1999
package er.reporting.examples;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class ERPage extends WOComponent {

    public ERPage(WOContext c){
        super(c);
    }

}
