// Generated by the WebObjects Wizard Mon Mar 22 11:53:37 US/Central 1999
package er.reporting.examples;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Intro extends WOComponent {

    public Intro(WOContext c){
        super(c);
    }


}
