package er.ajax.example;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at Apr 22, 2008 11:35:28 AM
public class ComponentRevealExample extends er.extensions.ERXComponent {
    public ComponentRevealExample(WOContext context) {
        super(context);
    }
}