package er.openid;

// Generated by the WOLips Templateengine Plug-in at Apr 22, 2007 9:09:53 AM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

/**
 * EROFormRedirectionPage is a simple implementation of OpenID form redirection.
 * 
 * @author mschrag
 */
public class EROFormRedirectionPage extends WOComponent implements IEROFormRedirectionPage {
  private String _redirectionUrl;

  public EROFormRedirectionPage(WOContext context) {
    super(context);
  }

  public void setRedirectionUrl(String redirectionUrl) {
    _redirectionUrl = redirectionUrl;
  }

  public String redirectionUrl() {
    return _redirectionUrl;
  }
}