// Generated by the WOLips Templateengine Plug-in at Apr 28, 2006 9:58:29 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class AccordionExample extends WOComponent {

  public AccordionExample(WOContext context) {
    super(context);
  }

}