// Generated by the WOLips Templateengine Plug-in at Feb 12, 2007 1:13:37 PM

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

import er.ajax.*;

public class AjaxGridExampleNavBar extends AjaxGridNavBar {

	public NSArray batchSizes = new NSArray(new Integer[] { Integer.valueOf(2), Integer.valueOf(4), Integer.valueOf(6), Integer.valueOf(8), Integer.valueOf(10) });
	public int batchSize;

	public AjaxGridExampleNavBar(WOContext context) {
		super(context);
	}

	/**
	 * @return value for BatchSizes from application configuration
	 */
	public NSArray batchSizes() {
		return batchSizes;
	}
}