// Generated by the WOLips Templateengine Plug-in at Mar 26, 2007 1:35:12 PM

import com.webobjects.appserver.*;

public class AjaxTabbedPanelDemo extends WOComponent {

    public AjaxTabbedPanelDemo(WOContext context) {
        super(context);
    }


    public boolean isSlowLoadingContentSelected() {
    	return "SlowLoadingContent".equals(theSession().selectedTab);
    }

    public void setIsSlowLoadingContentSelected(boolean isSelected) {
    	if (isSelected) theSession().selectedTab = "SlowLoadingContent";
    }

    public boolean isInlineContentSelected() {
    	return "InlineContent".equals(theSession().selectedTab);
    }

    public void setIsInlineContentSelected(boolean isSelected) {
    	if (isSelected) theSession().selectedTab = "InlineContent";
    }

    public Session theSession() {
    	return (Session)session();
    }

}