// Generated by the WOLips Templateengine Plug-in at 09.03.2006 16:24:23

import org.apache.log4j.Logger;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

import er.extensions.*;

public class Application extends ERXApplication {
    Logger log = Logger.getLogger(Application.class);
    public static void main(String argv[]) {
        ERXApplication.main(argv, Application.class);
    }

    public WOComponent pageWithName(String s, WOContext wocontext) {
		return super.pageWithName(s, wocontext);
	}

	public Application() {
        super();
        log.info("Welcome to " + this.name() + " !");
        log.info("Welcome to " + System.getProperty("java.class.path").replace(':', '\n') + " !");
        /* ** put your initialization code in here ** */
        setAllowsConcurrentRequestHandling(true);
        setDefaultRequestHandler(requestHandlerForKey(directActionRequestHandlerKey()));
    }
}