// Generated by the WOLips Templateengine Plug-in at 26.03.2006 01:19:23

import java.util.*;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;

public class AutoCompleteExample extends WOComponent {

	public static class Example {
		public Example(String name) {
			this.name = name;
			this.value = name.length();
		}
		public String name;
		public int value;
	}
    
    public String value;
    public Example currentValue;
    
    public NSMutableArray allValues;

    public AutoCompleteExample(WOContext context) {
        super(context);
        allValues = new NSMutableArray();
        Random rand = new Random();
        for(int i = 0; i < 1000; i++) {
            String s = "";
            for(int j = 0; j< 6; j++) {
                int c = rand.nextInt(26);
                s += Character.toString((char) ('A' + c));
            }
            Example example = new Example(s);
            allValues.addObject(example);
        }
        EOSortOrdering.sortArrayUsingKeyOrderArray(allValues, new NSArray(
                EOSortOrdering.sortOrderingWithKey("name", EOSortOrdering.CompareAscending)));
    }
 
    public NSArray currentValues() {
        NSMutableArray result = new NSMutableArray();
        for(Enumeration e = allValues.objectEnumerator(); e.hasMoreElements() && result.count() < 10;) {
        	Example c = (Example) e.nextElement();
            if(value == null || c.name.toLowerCase().indexOf(value.toLowerCase()) >= 0) {
                result.addObject(c);
            }
        }
        return result;
    }
}