// Generated by the WOLips Templateengine Plug-in at 26.03.2006 01:19:23

import java.util.Enumeration;

import org.apache.log4j.Logger;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;


public class AutoCompleteExample extends WOComponent {
    
	static Logger log = Logger.getLogger(AutoCompleteExample.class);

	public String value;
    public ExampleData currentValue;
    
    public NSArray allValues;

    public AutoCompleteExample(WOContext context) {
    	super(context);
    	allValues = ExampleData.exampleValues();
    }

    /**
     * This method gets called after every keystroke, we check the value variable and return the 10 entries
     * in allValues that contain this value.
     */
    public NSArray currentValues() {
        NSMutableArray result = new NSMutableArray();
        for(Enumeration e = allValues.objectEnumerator(); e.hasMoreElements() && result.count() < 10;) {
        	ExampleData c = (ExampleData) e.nextElement();
            if(value == null || c.name.toLowerCase().indexOf(value.toLowerCase()) >= 0) {
                result.addObject(c);
            }
        }
        return result;
    }
}