// Generated by the WOLips Templateengine Plug-in at 26.03.2006 01:19:23

import java.util.*;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;

public class AutoCompleteExample extends WOComponent {

    
    public String value;
    public String currentValue;
    
    public NSMutableArray allValues;

    public AutoCompleteExample(WOContext context) {
        super(context);
        allValues = new NSMutableArray();
        Random rand = new Random();
        for(int i = 0; i < 1000; i++) {
            String s = "";
            for(int j = 0; j< 6; j++) {
                int c = rand.nextInt(26);
                s += Character.toString((char) ('A' + c));
            }
            allValues.addObject(s);
        }
        EOSortOrdering.sortArrayUsingKeyOrderArray(allValues, new NSArray(
                EOSortOrdering.sortOrderingWithKey("toString", EOSortOrdering.CompareAscending)));
    }
 
    public NSArray currentValues() {
        NSMutableArray result = new NSMutableArray();
        for(Enumeration e = allValues.objectEnumerator(); e.hasMoreElements() && result.count() < 10;) {
            String c = (String) e.nextElement();
            if(value == null || c.toLowerCase().indexOf(value.toLowerCase()) >= 0) {
                result.addObject(c);
            }
        }
        return result;
    }
}