// Generated by the WOLips Templateengine Plug-in at Jun 28, 2006 1:09:19 AM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;

public class DependentListsExample extends WOComponent {
  private NSMutableArray _states;
  public State _repetitionState;
  public County _repetitionCounty;
  public State _selectedState;
  public State _selectedState2;
  public County _selectedCounty;
  public County _selectedCounty2;
  public County _selectedCounty3;
  public String _address;

  public DependentListsExample(WOContext context) {
    super(context);
    _states = new NSMutableArray();
    for (int stateNum = 0; stateNum < 30; stateNum++) {
      State state = new State("State " + stateNum);
      for (int countyNum = 0; countyNum < 30; countyNum++) {
        County county = new County("State " + state.name() + " - County " + countyNum);
        state.addCounty(county);
      }
      _states.addObject(state);
    }
  }

  public NSArray states() {
    return _states;
  }

  public static class State {
    private String _name;
    private NSMutableArray _counties;

    public State(String name) {
      _name = name;
      _counties = new NSMutableArray();
    }

    public String name() {
      return _name;
    }

    public void addCounty(County county) {
      _counties.addObject(county);
    }

    public NSArray counties() {
      return _counties;
    }
  }

  public static class County {
    public String _name;

    public County(String name) {
      _name = name;
    }

    public String name() {
      return _name;
    }
  }
}