// Generated by the WOLips Templateengine Plug-in at Jun 28, 2006 1:09:19 AM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;

public class DependentListsExample extends WOComponent {
  private NSMutableArray _states;
  private State _repetitionState;
  private County _repetitionCounty;
  private State _selectedState;
  private County _selectedCounty;

  public DependentListsExample(WOContext context) {
    super(context);
    _states = new NSMutableArray();
    for (int stateNum = 0; stateNum < 30; stateNum++) {
      State state = new State("State " + stateNum);
      for (int countyNum = 0; countyNum < 30; countyNum++) {
        County county = new County("State " + state.name() + " - County " + countyNum);
        state.addCounty(county);
      }
      _states.addObject(state);
    }
  }

  public NSArray states() {
    return _states;
  }

  public void setRepetitionState(State repetitionState) {
    _repetitionState = repetitionState;
  }

  public State repetitionState() {
    return _repetitionState;
  }

  public void setRepetitionCounty(County repetitionCounty) {
    _repetitionCounty = repetitionCounty;
  }

  public County repetitionCounty() {
    return _repetitionCounty;
  }

  public void setSelectedState(State selectedState) {
    _selectedState = selectedState;
  }

  public State selectedState() {
    return _selectedState;
  }

  public void setSelectedCounty(County selectedCounty) {
    _selectedCounty = selectedCounty;
  }

  public County selectedCounty() {
    return _selectedCounty;
  }

  public static class State {
    private String _name;
    private NSMutableArray _counties;

    public State(String name) {
      _name = name;
      _counties = new NSMutableArray();
    }

    public String name() {
      return _name;
    }

    public void addCounty(County county) {
      _counties.addObject(county);
    }

    public NSArray counties() {
      return _counties;
    }
  }

  public static class County {
    public String _name;

    public County(String name) {
      _name = name;
    }

    public String name() {
      return _name;
    }
  }
}