// Generated by the WOLips Templateengine Plug-in at 09.03.2006 16:24:23

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;

import er.extensions.ERXDirectAction;

public class DirectAction extends ERXDirectAction {
  public DirectAction(WORequest aRequest) {
    super(aRequest);
  }

  public WOActionResults defaultAction() {
    return pageWithName(Main.class.getName());
  }
}