// Generated by the WOLips Templateengine Plug-in at Mar 28, 2007 12:22:15 AM

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSData;

public class FileUploadExample extends WOComponent {
	public NSData _data;

	public FileUploadExample(WOContext context) {
		super(context);
	}

	public String test() {
		return null;
	}

	public WOActionResults uploadFinished() {
		System.out.println("FileUploadExample.uploadFinished: FINISHED!");
		if (_data != null) {
			System.out.println("FileUploadExample.uploadFinished: Data Size = " + _data.length());
		}
		return null;
	}
}