// Generated by the WOLips Templateengine Plug-in at Apr 30, 2006 11:09:21 PM

import com.webobjects.appserver.*;

public class InPlaceEditorExample extends WOComponent {
  private String myExampleValue;
  private String myMultilineValue;
  private String myStrippedValue;
  private int myNumericValue;

  public InPlaceEditorExample(WOContext context) {
    super(context);
    myExampleValue = "Test Value";
    myMultilineValue = "Multi<br>Line<br>Value";
    myStrippedValue = "Stripped Value";
    myNumericValue = 5;
  }

  public void setExampleValue(String _exampleValue) {
    myExampleValue = _exampleValue;
  }

  public String exampleValue() {
    return myExampleValue;
  }

  public void setMultilineValue(String _multilineValue) {
    myMultilineValue = _multilineValue;
  }

  public String multilineValue() {
    return myMultilineValue;
  }

  public void setStrippedValue(String _strippedValue) {
    myStrippedValue = _strippedValue;
  }

  public String strippedValue() {
    return myStrippedValue;
  }
  
  public void setNumericValue(int _numericValue) {
    myNumericValue = _numericValue;
  }
  
  public int numericValue() {
    return myNumericValue;
  }
}