// Generated by the WOLips Templateengine Plug-in at Apr 30, 2006 11:09:21 PM

import com.webobjects.appserver.*;

public class InPlaceEditorExample extends WOComponent {
  private String _exampleValue;
  private String _multilineValue;
  private String _strippedValue;
  private int _numericValue;

  public InPlaceEditorExample(WOContext context) {
    super(context);
    _exampleValue = "Test Value";
    _multilineValue = "Multi<br>Line<br>Value";
    _strippedValue = "Stripped Value";
    _numericValue = 5;
  }

  public void setExampleValue(String exampleValue) {
    _exampleValue = exampleValue;
  }

  public String exampleValue() {
    return _exampleValue;
  }

  public void setMultilineValue(String multilineValue) {
    _multilineValue = multilineValue;
  }

  public String multilineValue() {
    return _multilineValue;
  }

  public void setStrippedValue(String strippedValue) {
    _strippedValue = strippedValue;
  }

  public String strippedValue() {
    return _strippedValue;
  }
  
  public void setNumericValue(int numericValue) {
    _numericValue = numericValue;
  }
  
  public int numericValue() {
    return _numericValue;
  }
}