// Generated by the WOLips Templateengine Plug-in at Sep 21, 2006 9:19:23 PM

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSMutableArray;

public class LinkExample extends WOComponent {
  private boolean _showingSubComponent1;
  public NSMutableArray _words;
  public String _repetitionWord;
  public String _selectedWord; 

  public LinkExample(WOContext context) {
    super(context);
    _showingSubComponent1 = true;
    _words = new NSMutableArray();
    for (int i = 0; i < 10; i ++) {
      _words.addObject("Word #" + i);
    }
  }

  public WOActionResults wordSelected() {
    _selectedWord = _repetitionWord;
    System.out.println("LinkExample.wordSelected: " + _repetitionWord);
    return null;
  }
  
  public WOActionResults exampleAction() {
    System.out.println("LinkExample.exampleAction: Action Performed!");
    return null;
  }
  
  public String now() {
	  return String.valueOf(System.currentTimeMillis());
  }

  public WOActionResults replaceLinkAction() {
    WOActionResults results;
    if (_showingSubComponent1) {
      results = pageWithName(LinkExampleSubComponent2.class.getName());
    }
    else {
      results = pageWithName(LinkExampleSubComponent1.class.getName());
    }
    _showingSubComponent1 = !_showingSubComponent1;
    return results;
  }
  
  public WOActionResults onClickServerAction() {
	  System.out.println("LinkExample.onClickServerAction: Clicked");
	  return null;
  }
}