import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at 26.03.2008 12:58:41
public class ModalContainerExample extends WOComponent {
	public ModalContainerExample(WOContext context) {
		super(context);
	}
}