// Generated by the WOLips Templateengine Plug-in at May 22, 2006 8:46:37 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequest;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSMutableDictionary;

public class PopUpButtonExample extends WOComponent {
  private NSMutableDictionary myMap;
  private String myFirstItem;
  private String mySecondItem;
  private String mySelectedFirst;
  private String mySelectedSecond;

  public PopUpButtonExample(WOContext context) {
    super(context);
    myMap = new NSMutableDictionary();
    for (char firstChar = 'A'; firstChar <= 'Z'; firstChar++) {
      String key = String.valueOf(firstChar);
      NSMutableArray values = new NSMutableArray();
      for (int secondNum = 0; secondNum < 10; secondNum++) {
        String value = key + String.valueOf(secondNum);
        values.addObject(value);
      }
      myMap.setObjectForKey(values, key);
    }
  }

  public NSArray firstItems() {
    NSArray firstItems = myMap.allKeys();
    return firstItems;
  }

  public NSArray secondItems() {
    NSArray secondItems = (NSArray) myMap.objectForKey(mySelectedFirst);
    return secondItems;
  }

  public void setFirstItem(String _firstItem) {
    myFirstItem = _firstItem;
  }

  public String firstItem() {
    return myFirstItem;
  }

  public void setSecondItem(String _secondItem) {
    mySecondItem = _secondItem;
  }

  public String secondItem() {
    return mySecondItem;
  }

  public void setSelectedFirst(String _selectedFirst) {
    mySelectedFirst = _selectedFirst;
  }

  public String selectedFirst() {
    return mySelectedFirst;
  }

  public void setSelectedSecond(String _selectedSecond) {
    mySelectedSecond = _selectedSecond;
  }

  public String selectedSecond() {
    return mySelectedSecond;
  }

  public long time() {
    return System.currentTimeMillis();
  }
}