// Generated by the WOLips Templateengine Plug-in at 27.03.2006 10:13:46

import com.metaparadigm.dict.DictClient;
import com.webobjects.appserver.*;

public class ProxyExample extends WOComponent {
    
    private int counter = 0;
    private DictClient dict;
    
    public ProxyExample(WOContext context) {
        super(context);
    }

    public int addMore(int x) {
        return counter = counter + x;
    }
    
    public int add() {
        return ++counter;
    }
    
    public DictClient dict() {
        if (dict == null) {
            dict = new DictClient("dict.die.net");
        }
        return dict;
    }
}