// Generated by the WOLips Templateengine Plug-in at 09.03.2006 16:24:23

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOSession;

import er.ajax.*;

public class Session extends WOSession {
    
    /**
     * Overridden so that Ajax requests are not saved in the page cache.
     */
    public void savePage(WOComponent arg0) {
        if((context().response().headerForKey(AjaxUtils.AJAX_REQUEST_KEY) == null &&
                (context().response().userInfo() != null && context().response().userInfo().objectForKey(AjaxUtils.AJAX_REQUEST_KEY) == null))
                || context().response().userInfo() == null) {
            super.savePage(arg0);
        }
    }
    
}