// Generated by the WOLips Templateengine Plug-in at 09.03.2006 16:24:23

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOSession;

import er.ajax.AjaxProxy;

public class Session extends WOSession {
    
    /**
     * Overridden so that Ajax requests are not saved in the page cache.
     */
    public void savePage(WOComponent arg0) {
        if(context().response().headerForKey(AjaxProxy.AJAX_REQUEST_KEY) == null) {
            super.savePage(arg0);
        }
    }
    
}