// Generated by the WOLips Templateengine Plug-in at Apr 22, 2006 10:13:01 PM

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;

public class SortableListExample extends WOComponent {
  private NSArray myListItems;
  private ListItem myRepetitionListItem;

  public SortableListExample(WOContext _context) {
    super(_context);
    NSMutableArray listItems = new NSMutableArray();
    for (int i = 0; i < 10; i++) {
      listItems.addObject(new ListItem(listID() + "_" + i, "Element #" + i));
    }
    myListItems = listItems;
  }

  public String listID() {
    return "exampleList";
  }

  public void setListItems(NSArray _listItems) {
    myListItems = _listItems;
  }

  public NSArray listItems() {
    return myListItems;
  }

  public void setRepetitionListItem(ListItem _repetitionListItem) {
    myRepetitionListItem = _repetitionListItem;
  }

  public ListItem repetitionListItem() {
    return myRepetitionListItem;
  }

  public WOActionResults orderChanged() {
    System.out.println("SortableListExample.orderChanged: " + myListItems);
    return null;
  }

  protected static class ListItem {
    private String myID;
    private String myName;

    public ListItem(String _id, String _name) {
      myID = _id;
      myName = _name;
    }

    public String name() {
      return myName;
    }

    public String id() {
      return myID;
    }

    public String toString() {
      return "[ListItem: id = " + myID + "]";
    }
  }
}