// Generated by the WOLips Templateengine Plug-in at Nov 28, 2006 2:59:49 PM

import com.webobjects.appserver.*;

public class ToggleExample extends WOComponent {
	public boolean _toggleAreaVisible;
	public boolean _toggleAreaVisible2;
	public boolean _toggleAreaVisible3;
	public String _text;

	public ToggleExample(WOContext context) {
		super(context);
		_text = "This text should not change!";
	}
	
	public WOActionResults toggled1() {
		System.out.println("ToggleExample.toggled: toggled value 1 to " + _toggleAreaVisible);
		return null;
	}
	
	public WOActionResults toggled3() {
		System.out.println("ToggleExample.toggled: toggled value 3 to " + _toggleAreaVisible3);
		return null;
	}
}