// Generated by the WOLips Templateengine Plug-in at 27.03.2006 21:45:20

import com.webobjects.appserver.*;

public class UpdaterExample extends WOComponent {

    public UpdaterExample(WOContext context) {
        super(context);
    }

    public long test() {
        return System.currentTimeMillis();
    }

    public WOComponent someAction() {
        return pageWithName("Main");
    }
}