// Generated by the WOLips Templateengine Plug-in at 27.07.2006 20:03:39

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WODisplayGroup;
import com.webobjects.eocontrol.EOSortOrdering;
import com.webobjects.foundation.NSArray;

public class UpdateDisplayGroupExample extends WOComponent {
	
	public WODisplayGroup dg;
	public Object current;
	
	public UpdateDisplayGroupExample(WOContext context) {
		super(context);
		dg = new WODisplayGroup();
		dg.setObjectArray(ExampleData.exampleValues());
		dg.setNumberOfObjectsPerBatch(20);
	}
	
	private void setSortOrder(String name) {
		dg.setSortOrderings(new NSArray(
				EOSortOrdering.sortOrderingWithKey(name, EOSortOrdering.CompareAscending)));
		dg.qualifyDisplayGroup();
	}
	
	public long millis() {
		return System.currentTimeMillis();
	}
	
	public void sortByName() {
		setSortOrder("name");
	}
	
	public void sortByValue() {
		setSortOrder("value");
	}
	
	public void selectObject() {
		dg.setSelectedObject(current);
	}
	
	public void save() {
		// do nothing
	}
}