// Generated by the WOLips Templateengine Plug-in at Oct 1, 2006 2:16:32 PM

import com.webobjects.appserver.*;

public class Main extends WOComponent {

    public Main(WOContext context) {
        super(context);
    }

}