package er.directtoweb.components.dates._xhtml;

import com.webobjects.appserver.*;

import er.directtoweb.components.dates.ERD2WQueryDateRange;

// Generated by the WOLips Templateengine Plug-in at Jul 9, 2008 1:58:14 PM
public class ERD2WQueryDateRange2 extends ERD2WQueryDateRange {
    public ERD2WQueryDateRange2(WOContext context) {
        super(context);
    }
    
    // accessors
    public String minName() {
    	return d2wContext().valueForKey("name") + "_min";
    }
    
    public String maxName() {
    	return d2wContext().valueForKey("name") + "_max";
    }
}