package er.directtoweb.components.dates._xhtml;

import com.webobjects.appserver.WOContext;
import er.directtoweb.components.ERDCustomEditComponent;


// Generated by the WOLips Templateengine Plug-in at May 31, 2008 4:09:14 PM
public class ERDEditDateJavascript2 extends ERDCustomEditComponent {
    public ERDEditDateJavascript2(WOContext context) {
        super(context);
    }
}