package er.bugtracker.components;
// Generated by the WOLips Templateengine Plug-in at 07.05.2007 11:20:49

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WODisplayGroup;
import com.webobjects.eocontrol.EODataSource;

import er.directtoweb.ERD2WListPage;
import er.directtoweb.ERD2WPage;
import er.directtoweb.ERDCustomComponent;

/**
 * Simple display of some info on the top of the page.
 * @author ak
 *
 */
public class PageHeader extends ERDCustomComponent {

    public PageHeader(WOContext context) {
        super(context);
    }
    
    public String explainationKey() {
        return valueForBinding("pageConfiguration") + ".explaination";
    }
    
    public String titleKey() {
        return valueForBinding("pageConfiguration") + ".title";
    }
    
    public String title() {
        return (String) valueForBinding("displayNameForPageConfiguration");
    }
    
    public boolean synchronizesVariablesWithBindings() {
    	return false;
    }
    
    private Object tolerantValueForKeyPath(String key) {
        if (parent() instanceof ERD2WPage) {
            ERD2WListPage page = (ERD2WListPage) parent();
            return parent().valueForKeyPath(key);
        }        
        return null;
    }

    public EODataSource dataSource() {
        return (EODataSource) tolerantValueForKeyPath("dataSource");
    }

    public WODisplayGroup displayGroup() {
        return (WODisplayGroup) tolerantValueForKeyPath("displayGroup");
    }
}