package er.erxtest;

// Generated by the WOLips Templateengine Plug-in at Jan 24, 2007 2:11:22 AM

import junit.textui.TestRunner;
import er.erxtest.tests.ERXTestSuite;
import er.extensions.ERXApplication;

public class Application extends ERXApplication {
  public static void main(String argv[]) {
    ERXApplication.main(argv, Application.class);
  }

  public Application() {
    setAllowsConcurrentRequestHandling(true);
    setAutoOpenInBrowser(false);
  }

  @Override
  public void didFinishLaunching() {
    super.didFinishLaunching();
    TestRunner.run(ERXTestSuite.suite());
    System.exit(0);
  }
}