package er.directtoweb.components.repetitions._xhtml;

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.repetitions.ERDInspectPageRepetition;
import er.extensions.foundation.ERXStringUtilities;
import er.extensions.foundation.ERXValueUtilities;

// Generated by the WOLips Templateengine Plug-in at Aug 11, 2008 10:46:25 AM
public class ERDEditPageRepetition extends ERDInspectPageRepetition {
    public ERDEditPageRepetition(WOContext context) {
        super(context);
    }
    
    // accessors
	public String componentName() {
		return isAjax() ? "AjaxUpdateContainer" : "WOGenericContainer";
	}
	
	public boolean isAjax() {
		Object b = d2wContext().valueForKey("isAjax");
		return b != null ? ERXValueUtilities.booleanValue(b) : false;
	}
	
	public String propertyClassString() {
		return isManadatory() ? "propertyKey mandatory" : "propertyKey";
	}
	
	public boolean isManadatory() {
		Object b = d2wContext().valueForKey("isMandatory");
		return b != null ? ERXValueUtilities.booleanValue(b) : false;
	}
	
	public String contentClassString() {
		return "content " + d2wContext().componentName();
	}
	
	public boolean disabled() {
		return !hasSections();
	}
	
	public String attributeClassString() {
		String attributeClassString = "attribute " + ERXStringUtilities.safeIdentifierName(propertyKey());
		return hasTitle() ? attributeClassString + " tooltip" : attributeClassString;
	}
	
	private String title() {
		return (String) d2wContext().valueForKey("title");
	}
	
	private boolean hasTitle() {
		return (title() != null && !title().equals(""));
	}
}