package er.directtoweb.components.repetitions._xhtml;

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.repetitions.ERDInspectPageRepetition;
import er.extensions.foundation.ERXStringUtilities;

// Generated by the WOLips Templateengine Plug-in at Aug 8, 2008 1:10:56 PM
public class ERDInspectPageRepetition2 extends ERDInspectPageRepetition {
    public ERDInspectPageRepetition2(WOContext context) {
        super(context);
    }
    
    // accessors
	public String contentClassString() {
		return "content " + d2wContext().componentName();
	}
	
	public boolean disabled() {
		return !hasSections();
	}
	
	public String attributeClassString() {
		return "attribute " + ERXStringUtilities.safeIdentifierName(propertyKey()); 
	}
}