package er.extensions.components._xhtml;

import com.webobjects.appserver.*;
import er.extensions.components.ERXToManyRelationship;

// Generated by the WOLips Templateengine Plug-in at Aug 5, 2008 1:09:27 PM
public class ERXToManyRelationship2 extends ERXToManyRelationship {
    public ERXToManyRelationship2(WOContext context) {
        super(context);
    }
}