<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.wocommunity.wonder.frameworks</groupId>
		<artifactId>woadaptors</artifactId>
		<version>8.0.1-SNAPSHOT</version>
	</parent>
	<groupId>io.github.wocommunity.wonder.woadaptors</groupId>
	<artifactId>vertxwoadaptor</artifactId>
	<name>VertxWOAdaptor</name>
	<description>Project Wonder: A collection of frameworks designed for use with WebObjects.</description>
	<url>https://wocommunity.org</url>

	<organization>
		<name>WOCommunity</name>
		<url>http://www.wocommunity.org/</url>
	</organization>

	<licenses>
		<license>
			<name>NetStruxr Public Software License</name>
			<url>https://github.com/wocommunity/wonder/blob/master/Frameworks/Core/ERExtensions/Documentation/LICENSE.NPL</url>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>Ramsey Gurley</name>
			<email>ramseygurley@gmail.com</email>
			<organization>WOCommunity</organization>
			<organizationUrl>https://github.com/wocommunity/</organizationUrl>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:https://github.com/wocommunity/wonder.git</connection>
		<url>scm:git:https://github.com/wocommunity/wonder.git</url>
		<developerConnection>scm:git:https://github.com/wocommunity/wonder.git</developerConnection>
		<tag>HEAD</tag>
	</scm>
	<dependencies>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-webobjects</artifactId>
		</dependency>
		<dependency>
			<groupId>io.vertx</groupId>
			<artifactId>vertx-web</artifactId>
			<version>5.0.6</version>
		</dependency>
		<!-- for annotations like @Nullable -->
		<dependency>
			<groupId>io.vertx</groupId>
			<artifactId>vertx-codegen-api</artifactId>
			<version>5.0.6</version>
		</dependency>
		<dependency>
			<groupId>com.aayushatharva.brotli4j</groupId>
			<artifactId>brotli4j</artifactId>
			<version>1.20.0</version>
		</dependency>
		<dependency>
			<groupId>com.github.luben</groupId>
			<artifactId>zstd-jni</artifactId>
			<version>1.5.7-6</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk18on</artifactId>
			<version>1.83</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcpkix-jdk18on</artifactId>
			<version>1.83</version>
		</dependency>
	</dependencies>
</project>