// Generated by the WebObjects Wizard Sun Apr 04 22:59:37 US/Central 1999
package er.reporting.examples;

import er.reporting.*;
import er.grouping.*;

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;

public class ERPage extends WOComponent {

    public ERPage(WOContext c){
        super(c);
    }

}
