// Generated by the WebObjects Wizard Fri Mar 26 23:34:17 US/Central 1999
package er.reporting.examples;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class GroupingOptions extends WOComponent {

    public GroupingOptions(WOContext c){
        super(c);
    }

	public WOComponent doNothing(){
		return null;
	}

}
