package er.iui.components;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXComponent;

// Generated by the WOLips Templateengine Plug-in at Apr 2, 2008 10:55:20 PM

/**
 *
 * @binding label
 */
public class ERIUIPreference extends ERXComponent {
  public ERIUIPreference(WOContext context) {
    super(context);
  }

  @Override
  public boolean synchronizesVariablesWithBindings() {
    return false;
  }
}
