// Generated by the WOLips Templateengine Plug-in at May 22, 2008 5:06:36 PM

import com.webobjects.foundation.*;
import er.extensions.appserver.ERXApplication;
import er.extensions.localization.ERXLocalizer;


public class Application extends ERXApplication {
    public static void main(String argv[]) {
        ERXApplication.main(argv, Application.class);
    }

    public Application() {
        NSLog.out.appendln("Welcome to " + this.name() + " !");
        /* ** put your initialization code in here ** */
		setAllowsConcurrentRequestHandling(true);
		setDefaultRequestHandler(requestHandlerForKey(directActionRequestHandlerKey()));
    }
}