// Generated by the WebObjects Wizard Sun Oct 15 12:11:09 US/Pacific 2000

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;
import com.webobjects.directtoweb.*;

public class DemoListTemplate extends com.webobjects.directtoweb.D2WListPage {

    public DemoListTemplate(WOContext context) {
        super(context);
    }
    
    public boolean showReturn() { return nextPage()!=null; }    
    
    public boolean isEntityInspectable() {
        Integer isEntityInspectable=(Integer)d2wContext().valueForKey("isEntityInspectable");
        return isEntityReadOnly() && (isEntityInspectable!=null && isEntityInspectable.intValue()!=0);
    }
}
