// Generated by the WebObjects Wizard Sun Oct 15 11:34:41 US/Pacific 2000

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;

public class PageWrapper extends WOComponent {

    public PageWrapper(WOContext aContext) {
        super(aContext);
    }
}
