CREATE TABLE "ERCHELP_TEXT" (
	"ID" INTEGER NOT NULL,
	"KEY_" VARCHAR(100) NOT NULL,
	"VALUE_" VARCHAR(1000)
);

CREATE TABLE "ERCLOG_ENTRY" (
	"CREATED" TIMESTAMP NOT NULL,
	"ID" INTEGER NOT NULL,
	"TEXT_" VARCHAR(10000000) NOT NULL,
	"USER_ID" INTEGER NOT NULL
);

CREATE TABLE "ERCPREFER" (
	"ID" INTEGER NOT NULL,
	"KEY_" VARCHAR(100) NOT NULL,
	"USER_ID" INTEGER,
	"VALUE_" VARCHAR(10000000)
);

CREATE TABLE "ERCSTATIC" (
	"ID" INTEGER NOT NULL,
	"KEY_" VARCHAR(100) NOT NULL,
	"VALUE_" VARCHAR(1000)
);

SET UNIQUE = 1000000 FOR "ERCHELP_TEXT";

SET UNIQUE = 1000000 FOR "ERCLOG_ENTRY";

SET UNIQUE = 1000000 FOR "ERCPREFER";

SET UNIQUE = 1000000 FOR "ERCSTATIC";

ALTER TABLE "ERCHELP_TEXT" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCLOG_ENTRY" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCPREFER" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCSTATIC" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;



CREATE TABLE "ERCMAIL_MESSAG" (
	"BCC_ADDR" VARCHAR(1000),
	"CC_ADDR" VARCHAR(1000),
	"CONTENT_GZIPPED" INTEGER NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	"DATE_SENT" TIMESTAMP,
	"EXCEPTION_REASON" VARCHAR(1000),
	"FROM_ADDR" VARCHAR(255) NOT NULL,
	"ID" INTEGER NOT NULL,
	"IS_READ" INTEGER NOT NULL,
	"LAST_MODIFIED" TIMESTAMP NOT NULL,
	"PLAIN_TEXT_" VARCHAR(10000000),
	"plain_text_compressed" BLOB,
	"REPLY_TO_ADDR" VARCHAR(1000),
	"SHOULD_ARCHIVE_SENT_MAIL" INTEGER NOT NULL,
	"MAIL_STATE_ID" VARCHAR(4) NOT NULL,
	"TEXT_" VARCHAR(10000000),
	"TEXT_COMPRESSED" BLOB,
	"TITLE" VARCHAR(255) NOT NULL,
	"TO_ADDR" VARCHAR(1000) NOT NULL,
	"X_MAILER" VARCHAR(255)
);

CREATE TABLE "ERCMAIL_MESSAG_ARCHIVE" (
	"BCC_ADDR" VARCHAR(1000),
	"CC_ADDR" VARCHAR(1000),
	"CONTENT_GZIPPED" INTEGER NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	"DATE_SENT" TIMESTAMP,
	"EXCEPTION_REASON" VARCHAR(1000) NOT NULL,
	"FROM_ADDR" VARCHAR(255) NOT NULL,
	"ID" INTEGER NOT NULL,
	"IS_READ" INTEGER NOT NULL,
	"LAST_MODIFIED" TIMESTAMP NOT NULL,
	"PLAIN_TEXT_" VARCHAR(10000000),
	"plain_text_compressed" BLOB,
	"REPLY_TO_ADDR" VARCHAR(1000),
	"SHOULD_ARCHIVE_SENT_MAIL" INTEGER NOT NULL,
	"MAIL_STATE_ID" VARCHAR(4) NOT NULL,
	"TEXT_" VARCHAR(10000000) NOT NULL,
	"TEXT_COMPRESSED" BLOB,
	"TITLE" VARCHAR(255) NOT NULL,
	"TO_ADDR" VARCHAR(1000) NOT NULL,
	"X_MAILER" VARCHAR(255)
);

CREATE TABLE "ERCMESSAG_ATTACH" (
	"FILE_PATH" VARCHAR(1000) NOT NULL,
	"ID" INTEGER NOT NULL,
	"MAIL_MESSAG_ID" INTEGER NOT NULL,
	"MIME_TYPE" VARCHAR(255) NOT NULL
);

SET UNIQUE = 1000000 FOR "ERCMAIL_MESSAG_ARCHIVE";

SET UNIQUE = 1000000 FOR "ERCMAIL_MESSAG";

SET UNIQUE = 1000000 FOR "ERCMESSAG_ATTACH";

ALTER TABLE "ERCMAIL_MESSAG" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCMAIL_MESSAG_ARCHIVE" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ERCMESSAG_ATTACH" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;



CREATE TABLE "BUG" (
	"COMP_ID" INTEGER NOT NULL,
	"DATE_MODIFIED" TIMESTAMP,
	"DATE_SUBMITTED" TIMESTAMP,
	"FEATURE_REQUEST" TINYINT NOT NULL,
	"ID" INTEGER NOT NULL,
	"ORIGINATOR_ID" INTEGER NOT NULL,
	"PEOPLE_ID" INTEGER NOT NULL,
	"PREVIOUS_OWNER_ID" INTEGER,
	"PR_ID" VARCHAR(4) NOT NULL,
	"READ_" VARCHAR(1),
	"RELEASE_ID" INTEGER NOT NULL,
	"STATE_ID" VARCHAR(4) NOT NULL,
	"SUBJECT" VARCHAR(50) NOT NULL,
	"DESCRIPTION" VARCHAR(100000000)
);

CREATE TABLE "Comment" (
	"BUG_ID" INTEGER NOT NULL,
	"DATE_SUBMITTED" TIMESTAMP,
	"id" INTEGER NOT NULL,
	"ORIGINATOR_ID" INTEGER NOT NULL,
	"DESCRIPTION" VARCHAR(100000000)
);

CREATE TABLE "COMPONENT" (
	"ID" INTEGER NOT NULL,
	"PEOPLE_ID" INTEGER NOT NULL,
	"PARENT_ID" INTEGER,
	"DESCRIPTION" VARCHAR(100000000) NOT NULL
);

CREATE TABLE "DIFFICULTY" (
	"DESCRIPTION" VARCHAR(50) NOT NULL,
	"ID" INTEGER NOT NULL
);

CREATE TABLE "FRAMEW" (
	"ID" INTEGER NOT NULL,
	"NAME" VARCHAR(50) NOT NULL,
	"ORDERING" INTEGER NOT NULL,
	"OWNED_SINCE" TIMESTAMP,
	"USER_ID" INTEGER
);

CREATE TABLE "PEOPLE" (
	"EMAIL" VARCHAR(50),
	"ID" INTEGER NOT NULL,
	"IS_ACTIVE" TINYINT NOT NULL,
	"IS_ADMIN" TINYINT NOT NULL,
	"IS_CUSTOMER_SERVICE" TINYINT NOT NULL,
	"IS_ENGINEERING" TINYINT NOT NULL,
	"LOGIN" VARCHAR(16) NOT NULL,
	"NAME" VARCHAR(50),
	"PASSWORD" VARCHAR(16) NOT NULL,
	"TEAM" VARCHAR(16)
);

CREATE TABLE "PRIORITY" (
	"ID" VARCHAR(4) NOT NULL,
	"SORT_ORDER" INTEGER NOT NULL,
	"DESCRIPTION" VARCHAR(50) NOT NULL
);

CREATE TABLE "RELEASE" (
	"ID" INTEGER NOT NULL,
	"IS_OPEN" TINYINT NOT NULL,
	"NAME" VARCHAR(50) NOT NULL
);

CREATE TABLE "REQUIREMENT" (
	"COMP_ID" INTEGER NOT NULL,
	"DATE_MODIFIED" TIMESTAMP NOT NULL,
	"DATE_SUBMITTED" TIMESTAMP NOT NULL,
	"DIFFICULTY_ID" INTEGER,
	"FEATURE_REQUEST" TINYINT NOT NULL,
	"ID" INTEGER NOT NULL,
	"ORIGINATOR_ID" INTEGER NOT NULL,
	"PEOPLE_ID" INTEGER NOT NULL,
	"PREVIOUS_OWNER_ID" INTEGER,
	"PR_ID" VARCHAR(4) NOT NULL,
	"READ_" VARCHAR(1),
	"RELEASE_ID" INTEGER NOT NULL,
	"SUB_TYPE_ID" INTEGER,
	"REQ_TYPE_ID" INTEGER,
	"STATE_ID" VARCHAR(4) NOT NULL,
	"SUBJECT" VARCHAR(100) NOT NULL,
	"DESCRIPTION" VARCHAR(100000000)
);

CREATE TABLE "REQ_SUB_TYPE" (
	"REQ_SUB_TYPE_ID" INTEGER NOT NULL,
	"SUB_TYPE_DESC" VARCHAR(50) NOT NULL
);

CREATE TABLE "REQ_TYPE" (
	"REQ_TYPE_ID" INTEGER NOT NULL,
	"TYPE_DESCRIPTION" VARCHAR(50) NOT NULL
);

CREATE TABLE "STATE" (
	"ID" VARCHAR(4) NOT NULL,
	"SORT_ORDER" INTEGER NOT NULL,
	"DESCRIPTION" VARCHAR(50) NOT NULL
);

CREATE TABLE "TEST_ITEM" (
	"COMMENTS" VARCHAR(100000000),
	"MODULE_ID" INTEGER NOT NULL,
	"CONTROLLED" VARCHAR(50) NOT NULL,
	"DATE_CREATED" TIMESTAMP NOT NULL,
	"ID" INTEGER NOT NULL,
	"STATE_ID" VARCHAR(4) NOT NULL,
	"TESTED_BY_ID" INTEGER,
	"DESCRIPTION" VARCHAR(100000000),
	"TITLE" VARCHAR(100) NOT NULL
);

CREATE TABLE "TEST_ITEM_STATE" (
	"NAME" VARCHAR(50) NOT NULL,
	"ID" VARCHAR(4) NOT NULL,
	"SORT_ORDER" INTEGER NOT NULL
);

CREATE TABLE "BUG_TEST_ITEM" (
	"BUG_ID" INTEGER NOT NULL,
	"ID" INTEGER NOT NULL
);

CREATE TABLE "REQ_TEST_ITEM" (
	"BUG_ID" INTEGER NOT NULL,
	"ID" INTEGER NOT NULL
);

SET UNIQUE = 1000000 FOR "REQUIREMENT";

SET UNIQUE = 1000000 FOR "BUG";

SET UNIQUE = 1000000 FOR "Comment";

SET UNIQUE = 1000000 FOR "COMPONENT";

SET UNIQUE = 1000000 FOR "DIFFICULTY";

SET UNIQUE = 1000000 FOR "FRAMEW";

SET UNIQUE = 1000000 FOR "PEOPLE";

SET UNIQUE = 1000000 FOR "RELEASE";

SET UNIQUE = 1000000 FOR "REQ_SUB_TYPE";

SET UNIQUE = 1000000 FOR "REQ_TYPE";

SET UNIQUE = 1000000 FOR "TEST_ITEM";

ALTER TABLE "BUG" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "COMMENT" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "COMPONENT" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DIFFICULTY" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FRAMEW" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PEOPLE" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PRIORITY" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RELEASE" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REQUIREMENT" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REQ_SUB_TYPE" ADD PRIMARY KEY ("REQ_SUB_TYPE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REQ_TYPE" ADD PRIMARY KEY ("REQ_TYPE_ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "STATE" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_ITEM" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEST_ITEM_STATE" ADD PRIMARY KEY ("ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "BUG_TEST_ITEM" ADD PRIMARY KEY ("BUG_ID","ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REQ_TEST_ITEM" ADD PRIMARY KEY ("BUG_ID","ID") NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "BUG" ADD FOREIGN KEY ("RELEASE_ID") REFERENCES "RELEASE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BUG" ADD FOREIGN KEY ("STATE_ID") REFERENCES "STATE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BUG" ADD FOREIGN KEY ("PR_ID") REFERENCES "PRIORITY" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BUG" ADD FOREIGN KEY ("PREVIOUS_OWNER_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BUG" ADD FOREIGN KEY ("PEOPLE_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BUG" ADD FOREIGN KEY ("ORIGINATOR_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BUG" ADD FOREIGN KEY ("COMP_ID") REFERENCES "COMPONENT" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "COMMENT" ADD FOREIGN KEY ("ORIGINATOR_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "COMPONENT" ADD FOREIGN KEY ("PARENT_ID") REFERENCES "COMPONENT" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "COMPONENT" ADD FOREIGN KEY ("PEOPLE_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "FRAMEW" ADD FOREIGN KEY ("USER_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("RELEASE_ID") REFERENCES "RELEASE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("STATE_ID") REFERENCES "STATE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("REQ_TYPE_ID") REFERENCES "REQ_TYPE" ("REQ_TYPE_ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("SUB_TYPE_ID") REFERENCES "REQ_SUB_TYPE" ("REQ_SUB_TYPE_ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("PR_ID") REFERENCES "PRIORITY" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("PREVIOUS_OWNER_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("PEOPLE_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("ORIGINATOR_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("DIFFICULTY_ID") REFERENCES "DIFFICULTY" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQUIREMENT" ADD FOREIGN KEY ("COMP_ID") REFERENCES "COMPONENT" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TEST_ITEM" ADD FOREIGN KEY ("STATE_ID") REFERENCES "TEST_ITEM_STATE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TEST_ITEM" ADD FOREIGN KEY ("TESTED_BY_ID") REFERENCES "PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "TEST_ITEM" ADD FOREIGN KEY ("MODULE_ID") REFERENCES "COMPONENT" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "BUG_TEST_ITEM" ADD FOREIGN KEY ("ID") REFERENCES "TEST_ITEM" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQ_TEST_ITEM" ADD FOREIGN KEY ("ID") REFERENCES "TEST_ITEM" ("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "REQ_TEST_ITEM" ADD FOREIGN KEY ("BUG_ID") REFERENCES "REQUIREMENT" ("ID") DEFERRABLE INITIALLY DEFERRED;

