package er.selenium;
// Generated by the WOLips Templateengine Plug-in at 07.06.2007 17:57:30

import java.lang.reflect.Method;

import org.apache.log4j.Logger;

import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WOResponse;

import er.extensions.ERXProperties;
import er.extensions.ERXStatelessComponent;
import er.extensions.ERXUtilities;

public class SeleniumActionResultPage extends ERXStatelessComponent {
	private static final Logger log = Logger.getLogger(SeleniumTestSuitePage.class);
	
	public static final String ACTION_NAME_KEY = "actionName";

	public static final String SELENIUM_TESTS_DISABLED_MESSAGE = "Selenium tests are disabled.";
	public static final String ACTIONS_CLASS_NOT_FOUND_MESSAGE = "Actions class not found";
	public static final String ACTION_COMMAND_FAILED_MESSAGE = "Action command failed.";
	public static final String INVALID_ACTION_COMMAND_MESSAGE = "Invalid action command.";
	public static final String ACTION_COMMAND_SUCCEEDED_MESSAGE = "Action command succeeded.";
	
	private String _actionName;
	
    public SeleniumActionResultPage(WOContext context) {
        super(context);
    }
    
    public void setActionName(String name) {
    	_actionName = name;
    }
    
    public String actionName() {
    	return _actionName;
    }

    // @Override
    public void appendToResponse(WOResponse aResponse, WOContext aContext) {    	
		String actionResult;
		if (ERXProperties.booleanForKeyWithDefault("SeleniumTestsEnabled", false)) {
			String actionsClassName = ERXProperties.stringForKeyWithDefault("SeleniumActionsClass", SeleniumDefaultSetupActions.class.getName());

			try {
				Class c = Class.forName(actionsClassName);
                Method m = c.getMethod(_actionName, new Class[]{ WOResponse.class, WOContext.class });
                m.invoke(null, new Object[]{aResponse, aContext});
				actionResult = ACTION_COMMAND_SUCCEEDED_MESSAGE;
			} catch (ClassNotFoundException  e) {
				actionResult = ACTIONS_CLASS_NOT_FOUND_MESSAGE;
			} catch (NoSuchMethodException e) {
				actionResult = INVALID_ACTION_COMMAND_MESSAGE;
			} catch (Exception e) {
				log.error(e.toString());
				log.error(ERXUtilities.stackTrace(e));
				actionResult = ACTION_COMMAND_FAILED_MESSAGE;
			}

		} else {
			log.error("Selenium tests support is disabled. You can turn them on using SeleniumTestsEnabled=true in Properties files");
			actionResult = SELENIUM_TESTS_DISABLED_MESSAGE;
		}
		
		aResponse.appendContentString(actionResult);
    	super.appendToResponse(aResponse, aContext);
    }
}