name: Publish Wonder to the Maven Central Repository
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "wonder8"
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Install WebObjects
        run: |
          mkdir woinstalltmp
          cd woinstalltmp
          mvn io.github.wocommunity:woinstall-maven-plugin:woinstall
          cd ..
          rm -rf woinstalltmp
      - name: Configure git user
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
      - name: Checkout womodular
        uses: actions/checkout@v4
        with:
          repository: wocommunity/womodular
          path: ./womodular
          ref: master
      - name: Build womodular
        run: mvn clean install
        working-directory: ./womodular
      - name: Cleanup womodular
        run: rm -rf womodular
      - name: Test build
        run: mvn clean verify