// Generated by the WOLips Templateengine Plug-in at 12.02.2007 19:49:37

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2W;
import com.webobjects.directtoweb.ListPageInterface;
import com.webobjects.eoaccess.EODatabaseDataSource;
import com.webobjects.eocontrol.EOFetchSpecification;

public class Main extends WOComponent {

    public Main(WOContext context) {
        super(context); 
    }

    public WOComponent showList() {
        ListPageInterface nextPage = (ListPageInterface) D2W.factory().pageForConfigurationNamed("ListAjaxBug", session());
        EODatabaseDataSource ds = new EODatabaseDataSource(session().defaultEditingContext(), "Bug");
        ds.setFetchSpecification(new EOFetchSpecification("Bug", null, null));
        ds.fetchSpecification().setFetchLimit(5);
        nextPage.setDataSource(ds);
        return (WOComponent) nextPage;
    }
}